// Generated by tools/images.mjs from the client's image export. Do not edit by hand.
import type { ImageSource } from "./types";

export const blogImages: Record<string, ImageSource[]> = {
  "human-in-the-loop-data-capture": [
    {
      "src": "/blog/human-in-the-loop-data-capture-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/human-in-the-loop-data-capture-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "measuring-ai-roi-in-banking": [
    {
      "src": "/blog/measuring-ai-roi-in-banking-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/measuring-ai-roi-in-banking-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "why-accountable-ai-will-outlast-generative-ai": [
    {
      "src": "/blog/why-accountable-ai-will-outlast-generative-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/why-accountable-ai-will-outlast-generative-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "measuring-ai-roi-in-healthcare": [
    {
      "src": "/blog/measuring-ai-roi-in-healthcare-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/measuring-ai-roi-in-healthcare-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "latency-against-intelligence": [
    {
      "src": "/blog/latency-against-intelligence-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/latency-against-intelligence-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "measuring-the-roi-of-ai-productivity-tools": [
    {
      "src": "/blog/measuring-the-roi-of-ai-productivity-tools-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/measuring-the-roi-of-ai-productivity-tools-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-cost-of-a-missing-field": [
    {
      "src": "/blog/the-cost-of-a-missing-field-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-cost-of-a-missing-field-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-client-reporting-for-asset-managers": [
    {
      "src": "/blog/ai-client-reporting-for-asset-managers-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-client-reporting-for-asset-managers-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "where-agentic-ai-is-heading-in-regulated-industries": [
    {
      "src": "/blog/where-agentic-ai-is-heading-in-regulated-industries-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/where-agentic-ai-is-heading-in-regulated-industries-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-ai-operating-model-for-health-systems": [
    {
      "src": "/blog/the-ai-operating-model-for-health-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-ai-operating-model-for-health-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "input-integrity-for-agentic-systems": [
    {
      "src": "/blog/input-integrity-for-agentic-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/input-integrity-for-agentic-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "migrating-between-foundation-models-without-rewriting-your-stack": [
    {
      "src": "/blog/migrating-between-foundation-models-without-rewriting-your-stack-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/migrating-between-foundation-models-without-rewriting-your-stack-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-design-tools-compared": [
    {
      "src": "/blog/ai-design-tools-compared-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-design-tools-compared-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-treasury-and-cash-flow-forecasting": [
    {
      "src": "/blog/ai-for-treasury-and-cash-flow-forecasting-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-treasury-and-cash-flow-forecasting-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "latency-in-conversational-voice-ai": [
    {
      "src": "/blog/latency-in-conversational-voice-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/latency-in-conversational-voice-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "writing-the-anonymised-case-study": [
    {
      "src": "/blog/writing-the-anonymised-case-study-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/writing-the-anonymised-case-study-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "responsible-ai-in-healthcare": [
    {
      "src": "/blog/responsible-ai-in-healthcare-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/responsible-ai-in-healthcare-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "operationalizing-multilingual-voice-agents": [
    {
      "src": "/blog/operationalizing-multilingual-voice-agents-1.webp",
      "width": 657,
      "height": 656
    },
    {
      "src": "/blog/operationalizing-multilingual-voice-agents-2.webp",
      "width": 627,
      "height": 630
    }
  ],
  "multilingual-ai-customer-service-in-banking": [
    {
      "src": "/blog/multilingual-ai-customer-service-in-banking-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/multilingual-ai-customer-service-in-banking-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "claude-opus-4-6-and-agent-teams": [
    {
      "src": "/blog/claude-opus-4-6-and-agent-teams-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/claude-opus-4-6-and-agent-teams-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-review-debt-problem": [
    {
      "src": "/blog/the-review-debt-problem-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-review-debt-problem-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "engineering-natural-voice-agents": [
    {
      "src": "/blog/engineering-natural-voice-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/engineering-natural-voice-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "scaling-outbound-conversations-without-adding-headcount": [
    {
      "src": "/blog/scaling-outbound-conversations-without-adding-headcount-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/scaling-outbound-conversations-without-adding-headcount-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-pharma-manufacturing-and-quality": [
    {
      "src": "/blog/ai-in-pharma-manufacturing-and-quality-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-pharma-manufacturing-and-quality-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-algorithmic-trading": [
    {
      "src": "/blog/ai-in-algorithmic-trading-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-algorithmic-trading-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "designing-the-handoff": [
    {
      "src": "/blog/designing-the-handoff-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/designing-the-handoff-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "when-should-an-enterprise-upgrade-to-a-newer-model": [
    {
      "src": "/blog/when-should-an-enterprise-upgrade-to-a-newer-model-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/when-should-an-enterprise-upgrade-to-a-newer-model-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "red-teaming-financial-ai": [
    {
      "src": "/blog/red-teaming-financial-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/red-teaming-financial-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "how-a-regulated-lender-cleared-audit-on-first-pass": [
    {
      "src": "/blog/how-a-regulated-lender-cleared-audit-on-first-pass-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/how-a-regulated-lender-cleared-audit-on-first-pass-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-patient-facing-chatbots": [
    {
      "src": "/blog/ai-patient-facing-chatbots-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-patient-facing-chatbots-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "scaling-workforce-enablement-without-scaling-trainers": [
    {
      "src": "/blog/scaling-workforce-enablement-without-scaling-trainers-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/scaling-workforce-enablement-without-scaling-trainers-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "real-time-ai-avatars": [
    {
      "src": "/blog/real-time-ai-avatars-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/real-time-ai-avatars-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-economics-of-running-enterprise-ai": [
    {
      "src": "/blog/the-economics-of-running-enterprise-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-economics-of-running-enterprise-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "measuring-whether-training-actually-stuck": [
    {
      "src": "/blog/measuring-whether-training-actually-stuck-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/measuring-whether-training-actually-stuck-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-dispute-and-chargeback-automation": [
    {
      "src": "/blog/ai-for-dispute-and-chargeback-automation-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-dispute-and-chargeback-automation-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "generic-ai-vs-sector-fluent-ai": [
    {
      "src": "/blog/generic-ai-vs-sector-fluent-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/generic-ai-vs-sector-fluent-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "multimodal-ai-in-healthcare": [
    {
      "src": "/blog/multimodal-ai-in-healthcare-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/multimodal-ai-in-healthcare-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "onboarding-the-workforce-onto-agentic-workflows": [
    {
      "src": "/blog/onboarding-the-workforce-onto-agentic-workflows-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/onboarding-the-workforce-onto-agentic-workflows-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "choosing-an-enterprise-ai-assistant-platform": [
    {
      "src": "/blog/choosing-an-enterprise-ai-assistant-platform-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/choosing-an-enterprise-ai-assistant-platform-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "telematics-and-usage-based-insurance": [
    {
      "src": "/blog/telematics-and-usage-based-insurance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/telematics-and-usage-based-insurance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-frontier-bake-off": [
    {
      "src": "/blog/the-frontier-bake-off-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-frontier-bake-off-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-literacy-for-the-enterprise": [
    {
      "src": "/blog/ai-literacy-for-the-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-literacy-for-the-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "myth-a-more-powerful-model-solves-the-enterprise-ai-problem": [
    {
      "src": "/blog/myth-a-more-powerful-model-solves-the-enterprise-ai-problem-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/myth-a-more-powerful-model-solves-the-enterprise-ai-problem-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-early-sepsis-and-deterioration-prediction": [
    {
      "src": "/blog/ai-for-early-sepsis-and-deterioration-prediction-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-early-sepsis-and-deterioration-prediction-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-stress-testing-and-scenario-analysis": [
    {
      "src": "/blog/ai-for-stress-testing-and-scenario-analysis-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-stress-testing-and-scenario-analysis-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "training-teams-to-supervise-ai-agents": [
    {
      "src": "/blog/training-teams-to-supervise-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/training-teams-to-supervise-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "claude-opus-4-5-cheaper-frontier-coding": [
    {
      "src": "/blog/claude-opus-4-5-cheaper-frontier-coding-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/claude-opus-4-5-cheaper-frontier-coding-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "consolidating-the-ai-tool-stack": [
    {
      "src": "/blog/consolidating-the-ai-tool-stack-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/consolidating-the-ai-tool-stack-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "myth-a-convincing-demo-means-the-ai-is-ready": [
    {
      "src": "/blog/myth-a-convincing-demo-means-the-ai-is-ready-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/myth-a-convincing-demo-means-the-ai-is-ready-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "data-privacy-for-healthcare-ai": [
    {
      "src": "/blog/data-privacy-for-healthcare-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/data-privacy-for-healthcare-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-native-transformation": [
    {
      "src": "/blog/ai-native-transformation-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-native-transformation-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-debt-collections": [
    {
      "src": "/blog/ai-in-debt-collections-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-debt-collections-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "incident-response-for-ai-systems": [
    {
      "src": "/blog/incident-response-for-ai-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/incident-response-for-ai-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "what-a-production-ready-agent-actually-requires": [
    {
      "src": "/blog/what-a-production-ready-agent-actually-requires-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/what-a-production-ready-agent-actually-requires-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-complaint-handling-and-conduct-risk-detection": [
    {
      "src": "/blog/ai-for-complaint-handling-and-conduct-risk-detection-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-complaint-handling-and-conduct-risk-detection-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-regulatory-submissions-in-pharma": [
    {
      "src": "/blog/ai-for-regulatory-submissions-in-pharma-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-regulatory-submissions-in-pharma-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "gemini-3-pro-for-multimodal-and-agentic-workloads": [
    {
      "src": "/blog/gemini-3-pro-for-multimodal-and-agentic-workloads-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/gemini-3-pro-for-multimodal-and-agentic-workloads-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "building-a-golden-dataset-for-llm-evaluation": [
    {
      "src": "/blog/building-a-golden-dataset-for-llm-evaluation-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/building-a-golden-dataset-for-llm-evaluation-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-audio-for-brand-content": [
    {
      "src": "/blog/ai-audio-for-brand-content-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-audio-for-brand-content-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-portfolio-construction-and-risk-analytics": [
    {
      "src": "/blog/ai-in-portfolio-construction-and-risk-analytics-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-portfolio-construction-and-risk-analytics-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "data-governance-for-agentic-ai": [
    {
      "src": "/blog/data-governance-for-agentic-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/data-governance-for-agentic-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "buy-build-or-operate": [
    {
      "src": "/blog/buy-build-or-operate-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/buy-build-or-operate-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-healthcare-fraud-waste-and-abuse-detection": [
    {
      "src": "/blog/ai-for-healthcare-fraud-waste-and-abuse-detection-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-healthcare-fraud-waste-and-abuse-detection-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "adaptive-reasoning-arrives": [
    {
      "src": "/blog/adaptive-reasoning-arrives-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/adaptive-reasoning-arrives-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "event-driven-agent-architectures": [
    {
      "src": "/blog/event-driven-agent-architectures-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/event-driven-agent-architectures-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "voice-ai-in-banking-call-centers": [
    {
      "src": "/blog/voice-ai-in-banking-call-centers-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/voice-ai-in-banking-call-centers-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "voice-agents-for-the-contact-center": [
    {
      "src": "/blog/voice-agents-for-the-contact-center-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/voice-agents-for-the-contact-center-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-operating-model-your-risk-committee-will-approve": [
    {
      "src": "/blog/ai-operating-model-your-risk-committee-will-approve-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-operating-model-your-risk-committee-will-approve-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-connected-medical-devices": [
    {
      "src": "/blog/ai-in-connected-medical-devices-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-connected-medical-devices-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "an-agentic-ai-maturity-model": [
    {
      "src": "/blog/an-agentic-ai-maturity-model-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/an-agentic-ai-maturity-model-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "selecting-a-model-for-enterprise-rag": [
    {
      "src": "/blog/selecting-a-model-for-enterprise-rag-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/selecting-a-model-for-enterprise-rag-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "third-party-ai-risk-in-financial-services": [
    {
      "src": "/blog/third-party-ai-risk-in-financial-services-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/third-party-ai-risk-in-financial-services-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "accountability-in-autonomous-systems": [
    {
      "src": "/blog/accountability-in-autonomous-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/accountability-in-autonomous-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "deep-document-ai-in-financial-services": [
    {
      "src": "/blog/deep-document-ai-in-financial-services-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/deep-document-ai-in-financial-services-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "from-proof-of-concept-to-production": [
    {
      "src": "/blog/from-proof-of-concept-to-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/from-proof-of-concept-to-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-clinical-documentation-improvement": [
    {
      "src": "/blog/ai-for-clinical-documentation-improvement-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-clinical-documentation-improvement-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-health-insurance-claims-adjudication": [
    {
      "src": "/blog/ai-in-health-insurance-claims-adjudication-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-health-insurance-claims-adjudication-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "state-management-for-agents": [
    {
      "src": "/blog/state-management-for-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/state-management-for-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "claude-haiku-4-5-economics-of-small-fast-models": [
    {
      "src": "/blog/claude-haiku-4-5-economics-of-small-fast-models-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/claude-haiku-4-5-economics-of-small-fast-models-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "agreeing-the-number-before-you-start": [
    {
      "src": "/blog/agreeing-the-number-before-you-start-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/agreeing-the-number-before-you-start-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "credit-model-monitoring-and-drift-detection-through-the-economic-cycle": [
    {
      "src": "/blog/credit-model-monitoring-and-drift-detection-through-the-economic-cycle-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/credit-model-monitoring-and-drift-detection-through-the-economic-cycle-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "small-language-models-in-agentic-systems": [
    {
      "src": "/blog/small-language-models-in-agentic-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/small-language-models-in-agentic-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-voice-agents-in-healthcare-call-centers": [
    {
      "src": "/blog/ai-voice-agents-in-healthcare-call-centers-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-voice-agents-in-healthcare-call-centers-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "terminal-and-async-coding-agents-compared": [
    {
      "src": "/blog/terminal-and-async-coding-agents-compared-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/terminal-and-async-coding-agents-compared-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "choosing-models-for-clinical-assistants": [
    {
      "src": "/blog/choosing-models-for-clinical-assistants-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/choosing-models-for-clinical-assistants-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "structured-outputs-in-production": [
    {
      "src": "/blog/structured-outputs-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/structured-outputs-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "llms-for-earnings-calls-and-filings": [
    {
      "src": "/blog/llms-for-earnings-calls-and-filings-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/llms-for-earnings-calls-and-filings-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-cfo-test-for-enterprise-ai": [
    {
      "src": "/blog/the-cfo-test-for-enterprise-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-cfo-test-for-enterprise-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-surgical-planning-and-intraoperative-support": [
    {
      "src": "/blog/ai-in-surgical-planning-and-intraoperative-support-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-surgical-planning-and-intraoperative-support-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "operationalizing-ai-act-obligations": [
    {
      "src": "/blog/operationalizing-ai-act-obligations-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/operationalizing-ai-act-obligations-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-the-tools-you-already-use": [
    {
      "src": "/blog/ai-in-the-tools-you-already-use-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-the-tools-you-already-use-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-communications-surveillance": [
    {
      "src": "/blog/ai-communications-surveillance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-communications-surveillance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "claude-sonnet-4-5-and-long-horizon-agents": [
    {
      "src": "/blog/claude-sonnet-4-5-and-long-horizon-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/claude-sonnet-4-5-and-long-horizon-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "a-production-readiness-checklist-for-ai-agents": [
    {
      "src": "/blog/a-production-readiness-checklist-for-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/a-production-readiness-checklist-for-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "demand-and-inventory-intelligence-under-real-margins": [
    {
      "src": "/blog/demand-and-inventory-intelligence-under-real-margins-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/demand-and-inventory-intelligence-under-real-margins-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "monitoring-clinical-ai-in-production": [
    {
      "src": "/blog/monitoring-clinical-ai-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/monitoring-clinical-ai-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-mortgage-processing": [
    {
      "src": "/blog/ai-in-mortgage-processing-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-mortgage-processing-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "failure-analysis-for-ai-agents": [
    {
      "src": "/blog/failure-analysis-for-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/failure-analysis-for-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-best-models-for-ai-agents": [
    {
      "src": "/blog/the-best-models-for-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-best-models-for-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "order-delivery-and-returns-calls": [
    {
      "src": "/blog/order-delivery-and-returns-calls-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/order-delivery-and-returns-calls-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-nursing-assistants-and-workflow-support": [
    {
      "src": "/blog/ai-nursing-assistants-and-workflow-support-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-nursing-assistants-and-workflow-support-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "knowledge-graphs-and-rag": [
    {
      "src": "/blog/knowledge-graphs-and-rag-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/knowledge-graphs-and-rag-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "notions-workspace-agents": [
    {
      "src": "/blog/notions-workspace-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/notions-workspace-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "next-best-action-for-relationship-managers": [
    {
      "src": "/blog/next-best-action-for-relationship-managers-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/next-best-action-for-relationship-managers-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-supervisor-pattern-for-multi-agent-systems": [
    {
      "src": "/blog/the-supervisor-pattern-for-multi-agent-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-supervisor-pattern-for-multi-agent-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "claude-opus-4-1-for-enterprise-coding": [
    {
      "src": "/blog/claude-opus-4-1-for-enterprise-coding-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/claude-opus-4-1-for-enterprise-coding-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "personalisation-that-holds-up-at-scale": [
    {
      "src": "/blog/personalisation-that-holds-up-at-scale-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/personalisation-that-holds-up-at-scale-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-genomics-and-variant-interpretation": [
    {
      "src": "/blog/ai-in-genomics-and-variant-interpretation-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-genomics-and-variant-interpretation-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "accelerated-life-insurance-underwriting-with-ai": [
    {
      "src": "/blog/accelerated-life-insurance-underwriting-with-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/accelerated-life-insurance-underwriting-with-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "excessive-agency": [
    {
      "src": "/blog/excessive-agency-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/excessive-agency-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "when-anyone-can-generate-an-app": [
    {
      "src": "/blog/when-anyone-can-generate-an-app-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/when-anyone-can-generate-an-app-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "explainable-fraud-detection": [
    {
      "src": "/blog/explainable-fraud-detection-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/explainable-fraud-detection-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "agents-vs-workflow-automation": [
    {
      "src": "/blog/agents-vs-workflow-automation-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/agents-vs-workflow-automation-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "preserving-institutional-knowledge-in-government-with-agentic-ai": [
    {
      "src": "/blog/preserving-institutional-knowledge-in-government-with-agentic-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/preserving-institutional-knowledge-in-government-with-agentic-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-medical-record-summarization": [
    {
      "src": "/blog/ai-for-medical-record-summarization-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-medical-record-summarization-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "are-frontier-models-becoming-commodities": [
    {
      "src": "/blog/are-frontier-models-becoming-commodities-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/are-frontier-models-becoming-commodities-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "measuring-agent-roi": [
    {
      "src": "/blog/measuring-agent-roi-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/measuring-agent-roi-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "data-privacy-and-residency-for-ai-in-banking": [
    {
      "src": "/blog/data-privacy-and-residency-for-ai-in-banking-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/data-privacy-and-residency-for-ai-in-banking-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "customer-support-agents-compared": [
    {
      "src": "/blog/customer-support-agents-compared-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/customer-support-agents-compared-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-accreditation-and-citizen-services": [
    {
      "src": "/blog/ai-for-accreditation-and-citizen-services-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-accreditation-and-citizen-services-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-mental-health-support": [
    {
      "src": "/blog/ai-in-mental-health-support-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-mental-health-support-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "an-ai-risk-management-framework-for-agentic-systems": [
    {
      "src": "/blog/an-ai-risk-management-framework-for-agentic-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/an-ai-risk-management-framework-for-agentic-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "gpt-5-in-production": [
    {
      "src": "/blog/gpt-5-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/gpt-5-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "geospatial-ai-for-catastrophe-and-property-risk": [
    {
      "src": "/blog/geospatial-ai-for-catastrophe-and-property-risk-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/geospatial-ai-for-catastrophe-and-property-risk-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "durable-execution-for-long-running-agents": [
    {
      "src": "/blog/durable-execution-for-long-running-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/durable-execution-for-long-running-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "fair-and-auditable": [
    {
      "src": "/blog/fair-and-auditable-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/fair-and-auditable-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "on-prem-vs-cloud-ai-for-hospitals": [
    {
      "src": "/blog/on-prem-vs-cloud-ai-for-hospitals-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/on-prem-vs-cloud-ai-for-hospitals-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "agentic-browsers-in-the-enterprise": [
    {
      "src": "/blog/agentic-browsers-in-the-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/agentic-browsers-in-the-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "explainable-credit-decisions": [
    {
      "src": "/blog/explainable-credit-decisions-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/explainable-credit-decisions-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "continuous-evaluation-pipelines": [
    {
      "src": "/blog/continuous-evaluation-pipelines-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/continuous-evaluation-pipelines-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "function-calling-and-tool-use-compared": [
    {
      "src": "/blog/function-calling-and-tool-use-compared-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/function-calling-and-tool-use-compared-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "handling-sensitive-health-data": [
    {
      "src": "/blog/handling-sensitive-health-data-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/handling-sensitive-health-data-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "operating-mcp-servers-in-the-enterprise": [
    {
      "src": "/blog/operating-mcp-servers-in-the-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/operating-mcp-servers-in-the-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-the-ehr-reducing-click-burden": [
    {
      "src": "/blog/ai-in-the-ehr-reducing-click-burden-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-the-ehr-reducing-click-burden-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-esg-data-extraction-and-scoring": [
    {
      "src": "/blog/ai-for-esg-data-extraction-and-scoring-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-esg-data-extraction-and-scoring-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "chatgpt-agent-examined": [
    {
      "src": "/blog/chatgpt-agent-examined-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/chatgpt-agent-examined-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "scaling-agents-across-the-enterprise": [
    {
      "src": "/blog/scaling-agents-across-the-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/scaling-agents-across-the-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "kimi-k2-and-open-agentic-models": [
    {
      "src": "/blog/kimi-k2-and-open-agentic-models-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/kimi-k2-and-open-agentic-models-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-regulatory-change-management": [
    {
      "src": "/blog/ai-for-regulatory-change-management-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-regulatory-change-management-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "patient-reminder-and-scheduling-calls": [
    {
      "src": "/blog/patient-reminder-and-scheduling-calls-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/patient-reminder-and-scheduling-calls-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "validating-medical-imaging-ai": [
    {
      "src": "/blog/validating-medical-imaging-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/validating-medical-imaging-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "agentic-design-patterns": [
    {
      "src": "/blog/agentic-design-patterns-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/agentic-design-patterns-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "grok-4-for-the-enterprise": [
    {
      "src": "/blog/grok-4-for-the-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/grok-4-for-the-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "authorized-push-payment-scam-detection": [
    {
      "src": "/blog/authorized-push-payment-scam-detection-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/authorized-push-payment-scam-detection-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "approval-workflows-for-autonomous-agents": [
    {
      "src": "/blog/approval-workflows-for-autonomous-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/approval-workflows-for-autonomous-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "meeting-intelligence-tools-in-the-enterprise": [
    {
      "src": "/blog/meeting-intelligence-tools-in-the-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/meeting-intelligence-tools-in-the-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "cutting-administrative-load-in-healthcare-without-cutting": [
    {
      "src": "/blog/cutting-administrative-load-in-healthcare-without-cutting-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/cutting-administrative-load-in-healthcare-without-cutting-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-oncology-from-tumor-detection-to-treatment-planning": [
    {
      "src": "/blog/ai-in-oncology-from-tumor-detection-to-treatment-planning-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-oncology-from-tumor-detection-to-treatment-planning-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "monitoring-llms-in-production": [
    {
      "src": "/blog/monitoring-llms-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/monitoring-llms-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-ai-operating-model-for-banks": [
    {
      "src": "/blog/the-ai-operating-model-for-banks-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-ai-operating-model-for-banks-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "why-small-models-often-win-in-production": [
    {
      "src": "/blog/why-small-models-often-win-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/why-small-models-often-win-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "clinical-decision-support-that-keeps-the-clinician-in-the": [
    {
      "src": "/blog/clinical-decision-support-that-keeps-the-clinician-in-the-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/clinical-decision-support-that-keeps-the-clinician-in-the-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "inference-optimization-for-llm-workloads": [
    {
      "src": "/blog/inference-optimization-for-llm-workloads-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/inference-optimization-for-llm-workloads-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "explainable-ai-in-diagnosis": [
    {
      "src": "/blog/explainable-ai-in-diagnosis-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/explainable-ai-in-diagnosis-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-workflow-automation-compared": [
    {
      "src": "/blog/ai-workflow-automation-compared-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-workflow-automation-compared-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-policy-servicing-agents-in-insurance": [
    {
      "src": "/blog/ai-policy-servicing-agents-in-insurance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-policy-servicing-agents-in-insurance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "long-term-memory-for-agents": [
    {
      "src": "/blog/long-term-memory-for-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/long-term-memory-for-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "which-foundation-model-should-a-bank-standardize-on": [
    {
      "src": "/blog/which-foundation-model-should-a-bank-standardize-on-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/which-foundation-model-should-a-bank-standardize-on-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "fraud-flags-you-can-explain": [
    {
      "src": "/blog/fraud-flags-you-can-explain-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/fraud-flags-you-can-explain-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-population-health": [
    {
      "src": "/blog/ai-in-population-health-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-population-health-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "fair-lending-compliance-for-ai-credit-models": [
    {
      "src": "/blog/fair-lending-compliance-for-ai-credit-models-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/fair-lending-compliance-for-ai-credit-models-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "reducing-hallucinations-in-agentic-systems": [
    {
      "src": "/blog/reducing-hallucinations-in-agentic-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/reducing-hallucinations-in-agentic-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "gamma-against-canva-for-ai-generated-decks-and-design": [
    {
      "src": "/blog/gamma-against-canva-for-ai-generated-decks-and-design-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/gamma-against-canva-for-ai-generated-decks-and-design-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "red-teaming-ai-agents": [
    {
      "src": "/blog/red-teaming-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/red-teaming-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "on-prem-vs-cloud-llms-for-banks": [
    {
      "src": "/blog/on-prem-vs-cloud-llms-for-banks-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/on-prem-vs-cloud-llms-for-banks-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "compliant-collections-calls-at-scale": [
    {
      "src": "/blog/compliant-collections-calls-at-scale-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/compliant-collections-calls-at-scale-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "choosing-an-ai-model-for-clinical-assistants": [
    {
      "src": "/blog/choosing-an-ai-model-for-clinical-assistants-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/choosing-an-ai-model-for-clinical-assistants-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "llama-4-against-qwen-3-for-sovereign-enterprise-deployment": [
    {
      "src": "/blog/llama-4-against-qwen-3-for-sovereign-enterprise-deployment-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/llama-4-against-qwen-3-for-sovereign-enterprise-deployment-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "hybrid-search-for-enterprise-rag": [
    {
      "src": "/blog/hybrid-search-for-enterprise-rag-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/hybrid-search-for-enterprise-rag-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-actuarial-modeling": [
    {
      "src": "/blog/ai-in-actuarial-modeling-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-actuarial-modeling-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "automating-loan-document-checks-without-breaking-your-audit-trail": [
    {
      "src": "/blog/automating-loan-document-checks-without-breaking-your-audit-trail-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/automating-loan-document-checks-without-breaking-your-audit-trail-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "planning-in-ai-agents": [
    {
      "src": "/blog/planning-in-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/planning-in-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-remote-patient-monitoring": [
    {
      "src": "/blog/ai-in-remote-patient-monitoring-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-remote-patient-monitoring-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "claude-4-and-sustained-agentic-work": [
    {
      "src": "/blog/claude-4-and-sustained-agentic-work-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/claude-4-and-sustained-agentic-work-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "account-takeover-prevention": [
    {
      "src": "/blog/account-takeover-prevention-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/account-takeover-prevention-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "operationalizing-responsible-ai": [
    {
      "src": "/blog/operationalizing-responsible-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/operationalizing-responsible-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-underwriting-that-survives-a-model-risk-committee": [
    {
      "src": "/blog/ai-underwriting-that-survives-a-model-risk-committee-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-underwriting-that-survives-a-model-risk-committee-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-pharmacovigilance": [
    {
      "src": "/blog/ai-in-pharmacovigilance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-pharmacovigilance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-image-generation-for-brand-creative": [
    {
      "src": "/blog/ai-image-generation-for-brand-creative-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-image-generation-for-brand-creative-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "why-ai-benchmarks-dont-predict-production-performance": [
    {
      "src": "/blog/why-ai-benchmarks-dont-predict-production-performance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/why-ai-benchmarks-dont-predict-production-performance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "controlling-ai-hallucinations-in-financial-advice": [
    {
      "src": "/blog/controlling-ai-hallucinations-in-financial-advice-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/controlling-ai-hallucinations-in-financial-advice-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-best-coding-models-for-software-teams": [
    {
      "src": "/blog/the-best-coding-models-for-software-teams-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-best-coding-models-for-software-teams-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "prompt-caching-in-production": [
    {
      "src": "/blog/prompt-caching-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/prompt-caching-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-es-magico-product-suite": [
    {
      "src": "/blog/the-es-magico-product-suite-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-es-magico-product-suite-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-the-radiology-workflow": [
    {
      "src": "/blog/ai-in-the-radiology-workflow-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-the-radiology-workflow-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-trade-surveillance": [
    {
      "src": "/blog/ai-trade-surveillance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-trade-surveillance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "reasoning-tiers-compared": [
    {
      "src": "/blog/reasoning-tiers-compared-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/reasoning-tiers-compared-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "build-or-buy-your-agent-stack": [
    {
      "src": "/blog/build-or-buy-your-agent-stack-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/build-or-buy-your-agent-stack-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "generative-video-in-marketing": [
    {
      "src": "/blog/generative-video-in-marketing-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/generative-video-in-marketing-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-loan-default-prediction": [
    {
      "src": "/blog/ai-for-loan-default-prediction-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-loan-default-prediction-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "loupe-explained": [
    {
      "src": "/blog/loupe-explained-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/loupe-explained-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ci-cd-for-llm-applications": [
    {
      "src": "/blog/ci-cd-for-llm-applications-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ci-cd-for-llm-applications-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "controlling-hallucinations-in-medical-ai": [
    {
      "src": "/blog/controlling-hallucinations-in-medical-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/controlling-hallucinations-in-medical-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "llama-4-mixture-of-experts-and-sovereign-deployment": [
    {
      "src": "/blog/llama-4-mixture-of-experts-and-sovereign-deployment-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/llama-4-mixture-of-experts-and-sovereign-deployment-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "multi-agent-communication": [
    {
      "src": "/blog/multi-agent-communication-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/multi-agent-communication-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-investment-research": [
    {
      "src": "/blog/ai-for-investment-research-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-investment-research-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "gensparks-multi-agent-approach": [
    {
      "src": "/blog/gensparks-multi-agent-approach-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/gensparks-multi-agent-approach-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "compass-explained": [
    {
      "src": "/blog/compass-explained-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/compass-explained-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-clinical-trial-patient-matching": [
    {
      "src": "/blog/ai-for-clinical-trial-patient-matching-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-clinical-trial-patient-matching-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "testing-ai-agents": [
    {
      "src": "/blog/testing-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/testing-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-sme-lending": [
    {
      "src": "/blog/ai-in-sme-lending-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-sme-lending-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "gemini-against-claude-for-document-intelligence": [
    {
      "src": "/blog/gemini-against-claude-for-document-intelligence-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/gemini-against-claude-for-document-intelligence-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "audit-trails-for-autonomous-agents": [
    {
      "src": "/blog/audit-trails-for-autonomous-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/audit-trails-for-autonomous-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "prism-explained": [
    {
      "src": "/blog/prism-explained-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/prism-explained-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "bias-in-healthcare-ai": [
    {
      "src": "/blog/bias-in-healthcare-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/bias-in-healthcare-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "manus-and-the-autonomous-agent-promise": [
    {
      "src": "/blog/manus-and-the-autonomous-agent-promise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/manus-and-the-autonomous-agent-promise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "graph-ai-for-money-laundering-detection": [
    {
      "src": "/blog/graph-ai-for-money-laundering-detection-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/graph-ai-for-money-laundering-detection-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "sandboxing-agent-generated-code": [
    {
      "src": "/blog/sandboxing-agent-generated-code-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/sandboxing-agent-generated-code-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "long-context-reasoning-in-production": [
    {
      "src": "/blog/long-context-reasoning-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/long-context-reasoning-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "atlas-explained": [
    {
      "src": "/blog/atlas-explained-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/atlas-explained-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-patient-engagement-and-follow-up": [
    {
      "src": "/blog/ai-for-patient-engagement-and-follow-up-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-patient-engagement-and-follow-up-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "explainable-ai-in-finance": [
    {
      "src": "/blog/explainable-ai-in-finance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/explainable-ai-in-finance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "domain-ai-for-legal-work": [
    {
      "src": "/blog/domain-ai-for-legal-work-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/domain-ai-for-legal-work-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "function-calling-maturity": [
    {
      "src": "/blog/function-calling-maturity-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/function-calling-maturity-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "intelligent-document-processing-in-insurance": [
    {
      "src": "/blog/intelligent-document-processing-in-insurance-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/intelligent-document-processing-in-insurance-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "evio-explained": [
    {
      "src": "/blog/evio-explained-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/evio-explained-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "generative-ai-in-healthcare": [
    {
      "src": "/blog/generative-ai-in-healthcare-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/generative-ai-in-healthcare-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "why-benchmark-scores-dont-survive-contact-with-production": [
    {
      "src": "/blog/why-benchmark-scores-dont-survive-contact-with-production-1.webp",
      "width": 618,
      "height": 617
    },
    {
      "src": "/blog/why-benchmark-scores-dont-survive-contact-with-production-2.webp",
      "width": 696,
      "height": 697
    }
  ],
  "the-react-pattern-in-production": [
    {
      "src": "/blog/the-react-pattern-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-react-pattern-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "perpetual-kyc-continuous-risk-monitoring-without-drowning": [
    {
      "src": "/blog/perpetual-kyc-continuous-risk-monitoring-without-drowning-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/perpetual-kyc-continuous-risk-monitoring-without-drowning-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "automated-research-tools-in-production": [
    {
      "src": "/blog/automated-research-tools-in-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/automated-research-tools-in-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "llm-as-a-judge-where-automated-evaluation-works-and-where": [
    {
      "src": "/blog/llm-as-a-judge-where-automated-evaluation-works-and-where-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/llm-as-a-judge-where-automated-evaluation-works-and-where-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "multimodal-multilingual-ai": [
    {
      "src": "/blog/multimodal-multilingual-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/multimodal-multilingual-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-claims-denial-management": [
    {
      "src": "/blog/ai-for-claims-denial-management-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-for-claims-denial-management-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "grok-3-and-a-crowded-frontier": [
    {
      "src": "/blog/grok-3-and-a-crowded-frontier-1.webp",
      "width": 616,
      "height": 617
    },
    {
      "src": "/blog/grok-3-and-a-crowded-frontier-2.webp",
      "width": 621,
      "height": 617
    }
  ],
  "the-real-cost-of-running-ai-agents": [
    {
      "src": "/blog/the-real-cost-of-running-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-real-cost-of-running-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-personalization-in-banking": [
    {
      "src": "/blog/ai-personalization-in-banking-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-personalization-in-banking-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "getting-rag-to-hold-up-in-a-regulated-enterprise": [
    {
      "src": "/blog/getting-rag-to-hold-up-in-a-regulated-enterprise-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/getting-rag-to-hold-up-in-a-regulated-enterprise-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-in-digital-pathology": [
    {
      "src": "/blog/ai-in-digital-pathology-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-digital-pathology-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "securing-agentic-systems": [
    {
      "src": "/blog/securing-agentic-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/securing-agentic-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "controllable-thinking": [
    {
      "src": "/blog/controllable-thinking-1.webp",
      "width": 612,
      "height": 615
    },
    {
      "src": "/blog/controllable-thinking-2.webp",
      "width": 611,
      "height": 607
    }
  ],
  "glean-and-permissions-aware-enterprise-search": [
    {
      "src": "/blog/glean-and-permissions-aware-enterprise-search-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/glean-and-permissions-aware-enterprise-search-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "dora-and-ai-in-finance": [
    {
      "src": "/blog/dora-and-ai-in-finance-1.webp",
      "width": 610,
      "height": 611
    },
    {
      "src": "/blog/dora-and-ai-in-finance-2.webp",
      "width": 615,
      "height": 612
    }
  ],
  "context-engineering": [
    {
      "src": "/blog/context-engineering-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/context-engineering-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "agentic-workflows-vs-chatbots-and-rpa": [
    {
      "src": "/blog/agentic-workflows-vs-chatbots-and-rpa-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/agentic-workflows-vs-chatbots-and-rpa-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-for-patient-scheduling-and-no-show-reduction": [
    {
      "src": "/blog/ai-for-patient-scheduling-and-no-show-reduction-1.webp",
      "width": 691,
      "height": 687
    },
    {
      "src": "/blog/ai-for-patient-scheduling-and-no-show-reduction-2.webp",
      "width": 732,
      "height": 731
    }
  ],
  "synthetic-identity-fraud": [
    {
      "src": "/blog/synthetic-identity-fraud-1.webp",
      "width": 617,
      "height": 617
    },
    {
      "src": "/blog/synthetic-identity-fraud-2.webp",
      "width": 617,
      "height": 617
    }
  ],
  "measuring-rag-quality": [
    {
      "src": "/blog/measuring-rag-quality-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/measuring-rag-quality-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "is-open-source-catching-up-deepseek-against-gpt-and-claude": [
    {
      "src": "/blog/is-open-source-catching-up-deepseek-against-gpt-and-claude-1.webp",
      "width": 615,
      "height": 610
    },
    {
      "src": "/blog/is-open-source-catching-up-deepseek-against-gpt-and-claude-2.webp",
      "width": 612,
      "height": 612
    }
  ],
  "synthesia-against-heygen-for-enterprise-video-at-scale": [
    {
      "src": "/blog/synthesia-against-heygen-for-enterprise-video-at-scale-1.webp",
      "width": 687,
      "height": 687
    },
    {
      "src": "/blog/synthesia-against-heygen-for-enterprise-video-at-scale-2.webp",
      "width": 622,
      "height": 622
    }
  ],
  "ai-for-regulatory-reporting-and-reconciliation": [
    {
      "src": "/blog/ai-for-regulatory-reporting-and-reconciliation-1.webp",
      "width": 625,
      "height": 622
    },
    {
      "src": "/blog/ai-for-regulatory-reporting-and-reconciliation-2.webp",
      "width": 620,
      "height": 620
    }
  ],
  "why-most-enterprise-agent-pilots-never-reach-production": [
    {
      "src": "/blog/why-most-enterprise-agent-pilots-never-reach-production-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/why-most-enterprise-agent-pilots-never-reach-production-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "human-in-the-loop-that-survives-scrutiny": [
    {
      "src": "/blog/human-in-the-loop-that-survives-scrutiny-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/human-in-the-loop-that-survives-scrutiny-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "fda-regulated-ai": [
    {
      "src": "/blog/fda-regulated-ai-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/fda-regulated-ai-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "deepseek-r1-and-open-reasoning": [
    {
      "src": "/blog/deepseek-r1-and-open-reasoning-1.webp",
      "width": 615,
      "height": 607
    },
    {
      "src": "/blog/deepseek-r1-and-open-reasoning-2.webp",
      "width": 612,
      "height": 611
    }
  ],
  "agent-observability": [
    {
      "src": "/blog/agent-observability-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/agent-observability-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "insurance-fraud-detection-with-ai": [
    {
      "src": "/blog/insurance-fraud-detection-with-ai-1.webp",
      "width": 613,
      "height": 608
    },
    {
      "src": "/blog/insurance-fraud-detection-with-ai-2.webp",
      "width": 615,
      "height": 612
    }
  ],
  "explainability-by-design": [
    {
      "src": "/blog/explainability-by-design-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/explainability-by-design-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-medical-coding-and-autocoding": [
    {
      "src": "/blog/ai-medical-coding-and-autocoding-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-medical-coding-and-autocoding-2.webp",
      "width": 683,
      "height": 687
    }
  ],
  "elevenlabs-and-production-voice": [
    {
      "src": "/blog/elevenlabs-and-production-voice-1.webp",
      "width": 696,
      "height": 695
    },
    {
      "src": "/blog/elevenlabs-and-production-voice-2.webp",
      "width": 575,
      "height": 566
    }
  ],
  "engineering-guardrails-for-ai-agents": [
    {
      "src": "/blog/engineering-guardrails-for-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/engineering-guardrails-for-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "rag-for-banking-knowledge-bases": [
    {
      "src": "/blog/rag-for-banking-knowledge-bases-1.webp",
      "width": 612,
      "height": 607
    },
    {
      "src": "/blog/rag-for-banking-knowledge-bases-2.webp",
      "width": 616,
      "height": 617
    }
  ],
  "deepseek-v3-and-the-cost-shock": [
    {
      "src": "/blog/deepseek-v3-and-the-cost-shock-1.webp",
      "width": 612,
      "height": 616
    },
    {
      "src": "/blog/deepseek-v3-and-the-cost-shock-2.webp",
      "width": 626,
      "height": 627
    }
  ],
  "error-handling-for-ai-agents": [
    {
      "src": "/blog/error-handling-for-ai-agents-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/error-handling-for-ai-agents-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "designing-governance-into-agentic-ai-not-bolting-it-on": [
    {
      "src": "/blog/designing-governance-into-agentic-ai-not-bolting-it-on-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/designing-governance-into-agentic-ai-not-bolting-it-on-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "rag-for-clinical-knowledge": [
    {
      "src": "/blog/rag-for-clinical-knowledge-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/rag-for-clinical-knowledge-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "app-generation-tools-compared": [
    {
      "src": "/blog/app-generation-tools-compared-1.webp",
      "width": 695,
      "height": 690
    },
    {
      "src": "/blog/app-generation-tools-compared-2.webp",
      "width": 690,
      "height": 692
    }
  ],
  "designing-agentic-workflows": [
    {
      "src": "/blog/designing-agentic-workflows-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/designing-agentic-workflows-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "alternative-data-credit-scoring": [
    {
      "src": "/blog/alternative-data-credit-scoring-1.webp",
      "width": 617,
      "height": 623
    },
    {
      "src": "/blog/alternative-data-credit-scoring-2.webp",
      "width": 613,
      "height": 608
    }
  ],
  "gemini-2-0-flash-agentic-multimodal-default": [
    {
      "src": "/blog/gemini-2-0-flash-agentic-multimodal-default-1.webp",
      "width": 617,
      "height": 617
    },
    {
      "src": "/blog/gemini-2-0-flash-agentic-multimodal-default-2.webp",
      "width": 617,
      "height": 615
    }
  ],
  "what-hardened-means-in-enterprise-ai": [
    {
      "src": "/blog/what-hardened-means-in-enterprise-ai-1.webp",
      "width": 687,
      "height": 690
    },
    {
      "src": "/blog/what-hardened-means-in-enterprise-ai-2.webp",
      "width": 687,
      "height": 693
    }
  ],
  "ai-in-drug-discovery": [
    {
      "src": "/blog/ai-in-drug-discovery-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/ai-in-drug-discovery-2.webp",
      "width": 493,
      "height": 490
    }
  ],
  "the-model-context-protocol": [
    {
      "src": "/blog/the-model-context-protocol-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/the-model-context-protocol-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-sanctions-screening": [
    {
      "src": "/blog/ai-sanctions-screening-1.webp",
      "width": 617,
      "height": 617
    },
    {
      "src": "/blog/ai-sanctions-screening-2.webp",
      "width": 613,
      "height": 487
    }
  ],
  "microsoft-365-copilot-in-production": [
    {
      "src": "/blog/microsoft-365-copilot-in-production-1.webp",
      "width": 728,
      "height": 727
    },
    {
      "src": "/blog/microsoft-365-copilot-in-production-2.webp",
      "width": 657,
      "height": 653
    }
  ],
  "llm-evaluation-framework-your-team-will-actually-use": [
    {
      "src": "/blog/llm-evaluation-framework-your-team-will-actually-use-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/llm-evaluation-framework-your-team-will-actually-use-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "the-architecture-behind-our-platform": [
    {
      "src": "/blog/the-architecture-behind-our-platform-1.webp",
      "width": 691,
      "height": 687
    },
    {
      "src": "/blog/the-architecture-behind-our-platform-2.webp",
      "width": 692,
      "height": 687
    }
  ],
  "ai-in-revenue-cycle-management": [
    {
      "src": "/blog/ai-in-revenue-cycle-management-1.webp",
      "width": 613,
      "height": 616
    },
    {
      "src": "/blog/ai-in-revenue-cycle-management-2.webp",
      "width": 612,
      "height": 611
    }
  ],
  "agent-assist-for-banking-contact-centers": [
    {
      "src": "/blog/agent-assist-for-banking-contact-centers-1.webp",
      "width": 621,
      "height": 617
    },
    {
      "src": "/blog/agent-assist-for-banking-contact-centers-2.webp",
      "width": 612,
      "height": 622
    }
  ],
  "from-preview-to-production": [
    {
      "src": "/blog/from-preview-to-production-1.webp",
      "width": 618,
      "height": 613
    },
    {
      "src": "/blog/from-preview-to-production-2.webp",
      "width": 615,
      "height": 615
    }
  ],
  "deploying-ai-agents-at-scale": [
    {
      "src": "/blog/deploying-ai-agents-at-scale-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/deploying-ai-agents-at-scale-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "ai-underwriting-in-p-c-insurance": [
    {
      "src": "/blog/ai-underwriting-in-p-c-insurance-1.webp",
      "width": 613,
      "height": 607
    },
    {
      "src": "/blog/ai-underwriting-in-p-c-insurance-2.webp",
      "width": 621,
      "height": 620
    }
  ],
  "multi-agent-systems": [
    {
      "src": "/blog/multi-agent-systems-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/multi-agent-systems-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "operating-principles-behind-every-es-magico-engagement": [
    {
      "src": "/blog/operating-principles-behind-every-es-magico-engagement-1.webp",
      "width": 592,
      "height": 597
    },
    {
      "src": "/blog/operating-principles-behind-every-es-magico-engagement-2.webp",
      "width": 690,
      "height": 685
    }
  ],
  "hipaa-compliant-ai": [
    {
      "src": "/blog/hipaa-compliant-ai-1.webp",
      "width": 592,
      "height": 592
    },
    {
      "src": "/blog/hipaa-compliant-ai-2.webp",
      "width": 602,
      "height": 597
    }
  ],
  "heygen-and-synthetic-video": [
    {
      "src": "/blog/heygen-and-synthetic-video-1.webp",
      "width": 636,
      "height": 641
    },
    {
      "src": "/blog/heygen-and-synthetic-video-2.webp",
      "width": 698,
      "height": 695
    }
  ],
  "open-or-closed-framework-for-choosing-foundation-models": [
    {
      "src": "/blog/open-or-closed-framework-for-choosing-foundation-models-1.webp",
      "width": 621,
      "height": 617
    },
    {
      "src": "/blog/open-or-closed-framework-for-choosing-foundation-models-2.webp",
      "width": 615,
      "height": 615
    }
  ],
  "defending-agents-against-prompt-injection": [
    {
      "src": "/blog/defending-agents-against-prompt-injection-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/defending-agents-against-prompt-injection-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "model-risk-management-for-generative-ai": [
    {
      "src": "/blog/model-risk-management-for-generative-ai-1.webp",
      "width": 622,
      "height": 622
    },
    {
      "src": "/blog/model-risk-management-for-generative-ai-2.webp",
      "width": 615,
      "height": 621
    }
  ],
  "ai-native-vs-ai-first": [
    {
      "src": "/blog/ai-native-vs-ai-first-1.webp",
      "width": 692,
      "height": 687
    },
    {
      "src": "/blog/ai-native-vs-ai-first-2.webp",
      "width": 692,
      "height": 688
    }
  ],
  "ai-symptom-checkers-and-triage-chatbots": [
    {
      "src": "/blog/ai-symptom-checkers-and-triage-chatbots-1.webp",
      "width": 461,
      "height": 465
    },
    {
      "src": "/blog/ai-symptom-checkers-and-triage-chatbots-2.webp",
      "width": 480,
      "height": 476
    }
  ],
  "llm-cost-optimization": [
    {
      "src": "/blog/llm-cost-optimization-1.webp",
      "width": 1024,
      "height": 1024
    },
    {
      "src": "/blog/llm-cost-optimization-2.webp",
      "width": 1024,
      "height": 1024
    }
  ],
  "context-windows-explained-for-operators": [
    {
      "src": "/blog/context-windows-explained-for-operators-1.webp",
      "width": 612,
      "height": 612
    },
    {
      "src": "/blog/context-windows-explained-for-operators-2.webp",
      "width": 616,
      "height": 613
    }
  ],
  "agentforce-examined": [
    {
      "src": "/blog/agentforce-examined-1.webp",
      "width": 697,
      "height": 697
    },
    {
      "src": "/blog/agentforce-examined-2.webp",
      "width": 698,
      "height": 697
    }
  ],
  "robo-advisors-and-ai-in-wealth-management": [
    {
      "src": "/blog/robo-advisors-and-ai-in-wealth-management-1.webp",
      "width": 618,
      "height": 622
    },
    {
      "src": "/blog/robo-advisors-and-ai-in-wealth-management-2.webp",
      "width": 622,
      "height": 618
    }
  ],
  "llmops-in-practice": [
    {
      "src": "/blog/llmops-in-practice-1.webp",
      "width": 612,
      "height": 612
    },
    {
      "src": "/blog/llmops-in-practice-2.webp",
      "width": 615,
      "height": 615
    }
  ],
  "why-enterprises-choose-es-magico-in-regulated-environments": [
    {
      "src": "/blog/why-enterprises-choose-es-magico-in-regulated-environments-1.webp",
      "width": 687,
      "height": 687
    },
    {
      "src": "/blog/why-enterprises-choose-es-magico-in-regulated-environments-2.webp",
      "width": 696,
      "height": 690
    }
  ],
  "ambient-clinical-documentation": [
    {
      "src": "/blog/ambient-clinical-documentation-1.webp",
      "width": 395,
      "height": 392
    },
    {
      "src": "/blog/ambient-clinical-documentation-2.webp",
      "width": 497,
      "height": 495
    }
  ],
  "ai-in-insurance-claims-processing": [
    {
      "src": "/blog/ai-in-insurance-claims-processing-1.webp",
      "width": 620,
      "height": 623
    },
    {
      "src": "/blog/ai-in-insurance-claims-processing-2.webp",
      "width": 615,
      "height": 620
    }
  ],
  "agent-memory-systems": [
    {
      "src": "/blog/agent-memory-systems-1.webp",
      "width": 612,
      "height": 617
    },
    {
      "src": "/blog/agent-memory-systems-2.webp",
      "width": 613,
      "height": 617
    }
  ],
  "computer-use-is-here-but-agentic-readiness-isnt": [
    {
      "src": "/blog/computer-use-is-here-but-agentic-readiness-isnt-1.webp",
      "width": 538,
      "height": 520
    },
    {
      "src": "/blog/computer-use-is-here-but-agentic-readiness-isnt-2.webp",
      "width": 617,
      "height": 366
    }
  ],
  "cursor-in-the-enterprise": [
    {
      "src": "/blog/cursor-in-the-enterprise-1.webp",
      "width": 692,
      "height": 688
    },
    {
      "src": "/blog/cursor-in-the-enterprise-2.webp",
      "width": 606,
      "height": 605
    }
  ],
  "agentic-rag-when-retrieval-becomes-a-decision": [
    {
      "src": "/blog/agentic-rag-when-retrieval-becomes-a-decision-1.webp",
      "width": 611,
      "height": 608
    },
    {
      "src": "/blog/agentic-rag-when-retrieval-becomes-a-decision-2.webp",
      "width": 612,
      "height": 610
    }
  ],
  "inside-es-magico": [
    {
      "src": "/blog/inside-es-magico-1.webp",
      "width": 617,
      "height": 517
    },
    {
      "src": "/blog/inside-es-magico-2.webp",
      "width": 538,
      "height": 532
    }
  ],
  "ai-for-prior-authorization": [
    {
      "src": "/blog/ai-for-prior-authorization-1.webp",
      "width": 656,
      "height": 645
    },
    {
      "src": "/blog/ai-for-prior-authorization-2.webp",
      "width": 813,
      "height": 672
    }
  ],
  "aml-transaction-monitoring-with-ai": [
    {
      "src": "/blog/aml-transaction-monitoring-with-ai-1.webp",
      "width": 691,
      "height": 693
    },
    {
      "src": "/blog/aml-transaction-monitoring-with-ai-2.webp",
      "width": 622,
      "height": 622
    }
  ],
  "qwen2-5-for-regulated-workloads": [
    {
      "src": "/blog/qwen2-5-for-regulated-workloads-1.webp",
      "width": 576,
      "height": 582
    },
    {
      "src": "/blog/qwen2-5-for-regulated-workloads-2.webp",
      "width": 854,
      "height": 457
    }
  ],
  "human-in-the-loop-design": [
    {
      "src": "/blog/human-in-the-loop-design-1.webp",
      "width": 636,
      "height": 637
    },
    {
      "src": "/blog/human-in-the-loop-design-2.webp",
      "width": 613,
      "height": 610
    }
  ],
  "ai-in-kyc-and-customer-onboarding": [
    {
      "src": "/blog/ai-in-kyc-and-customer-onboarding-1.webp",
      "width": 499,
      "height": 530
    },
    {
      "src": "/blog/ai-in-kyc-and-customer-onboarding-2.webp",
      "width": 1200,
      "height": 594
    }
  ],
  "why-most-enterprise-ai-stalls-after-the-pilot": [
    {
      "src": "/blog/why-most-enterprise-ai-stalls-after-the-pilot-1.webp",
      "width": 615,
      "height": 595
    },
    {
      "src": "/blog/why-most-enterprise-ai-stalls-after-the-pilot-2.webp",
      "width": 619,
      "height": 496
    }
  ],
  "clinical-decision-support-with-ai": [
    {
      "src": "/blog/clinical-decision-support-with-ai-1.webp",
      "width": 872,
      "height": 617
    },
    {
      "src": "/blog/clinical-decision-support-with-ai-2.webp",
      "width": 780,
      "height": 523
    }
  ],
  "governing-agentic-ai": [
    {
      "src": "/blog/governing-agentic-ai-1.webp",
      "width": 622,
      "height": 622
    },
    {
      "src": "/blog/governing-agentic-ai-2.webp",
      "width": 620,
      "height": 618
    }
  ],
  "notebooklm-and-source-grounded-ai": [
    {
      "src": "/blog/notebooklm-and-source-grounded-ai-1.webp",
      "width": 620,
      "height": 620
    },
    {
      "src": "/blog/notebooklm-and-source-grounded-ai-2.webp",
      "width": 541,
      "height": 540
    }
  ],
  "reasoning-models-reach-the-enterprise": [
    {
      "src": "/blog/reasoning-models-reach-the-enterprise-1.webp",
      "width": 615,
      "height": 580
    },
    {
      "src": "/blog/reasoning-models-reach-the-enterprise-2.webp",
      "width": 619,
      "height": 562
    }
  ],
  "ai-credit-scoring-and-underwriting": [
    {
      "src": "/blog/ai-credit-scoring-and-underwriting-1.webp",
      "width": 562,
      "height": 525
    },
    {
      "src": "/blog/ai-credit-scoring-and-underwriting-2.webp",
      "width": 603,
      "height": 517
    }
  ],
  "evaluating-ai-agents": [
    {
      "src": "/blog/evaluating-ai-agents-1.webp",
      "width": 593,
      "height": 552
    },
    {
      "src": "/blog/evaluating-ai-agents-2.webp",
      "width": 606,
      "height": 314
    }
  ],
  "deploying-ai-is-easy-operationalising-it-is-the-work": [
    {
      "src": "/blog/deploying-ai-is-easy-operationalising-it-is-the-work-1.webp",
      "width": 589,
      "height": 445
    },
    {
      "src": "/blog/deploying-ai-is-easy-operationalising-it-is-the-work-2.webp",
      "width": 667,
      "height": 524
    }
  ],
  "ai-governance-in-healthcare": [
    {
      "src": "/blog/ai-governance-in-healthcare-1.webp",
      "width": 1045,
      "height": 768
    },
    {
      "src": "/blog/ai-governance-in-healthcare-2.webp",
      "width": 743,
      "height": 608
    }
  ],
  "llm-tool-calling-in-production": [
    {
      "src": "/blog/llm-tool-calling-in-production-1.webp",
      "width": 894,
      "height": 335
    },
    {
      "src": "/blog/llm-tool-calling-in-production-2.webp",
      "width": 608,
      "height": 401
    }
  ],
  "perplexity-as-an-enterprise-answer-engine": [
    {
      "src": "/blog/perplexity-as-an-enterprise-answer-engine-1.webp",
      "width": 631,
      "height": 628
    },
    {
      "src": "/blog/perplexity-as-an-enterprise-answer-engine-2.webp",
      "width": 673,
      "height": 670
    }
  ],
  "ai-governance-in-financial-services": [
    {
      "src": "/blog/ai-governance-in-financial-services-1.webp",
      "width": 563,
      "height": 496
    },
    {
      "src": "/blog/ai-governance-in-financial-services-2.webp",
      "width": 605,
      "height": 399
    }
  ],
  "llama-3-1-405b-and-the-case-for-open-weight-models": [
    {
      "src": "/blog/llama-3-1-405b-and-the-case-for-open-weight-models-1.webp",
      "width": 586,
      "height": 329
    },
    {
      "src": "/blog/llama-3-1-405b-and-the-case-for-open-weight-models-2.webp",
      "width": 327,
      "height": 460
    }
  ],
  "agent-orchestration-patterns": [
    {
      "src": "/blog/agent-orchestration-patterns-1.webp",
      "width": 605,
      "height": 563
    },
    {
      "src": "/blog/agent-orchestration-patterns-2.webp",
      "width": 587,
      "height": 367
    }
  ],
  "consultant-integrator-or-operator": [
    {
      "src": "/blog/consultant-integrator-or-operator-1.webp",
      "width": 891,
      "height": 502
    },
    {
      "src": "/blog/consultant-integrator-or-operator-2.webp",
      "width": 827,
      "height": 375
    }
  ],
  "ai-in-medical-imaging": [
    {
      "src": "/blog/ai-in-medical-imaging-1.webp",
      "width": 977,
      "height": 428
    },
    {
      "src": "/blog/ai-in-medical-imaging-2.webp",
      "width": 955,
      "height": 691
    }
  ],
  "ai-chatbots-in-banking": [
    {
      "src": "/blog/ai-chatbots-in-banking-1.webp",
      "width": 619,
      "height": 589
    },
    {
      "src": "/blog/ai-chatbots-in-banking-2.webp",
      "width": 632,
      "height": 487
    }
  ],
  "why-ai-agents-fail-in-production": [
    {
      "src": "/blog/why-ai-agents-fail-in-production-1.webp",
      "width": 1199,
      "height": 410
    },
    {
      "src": "/blog/why-ai-agents-fail-in-production-2.webp",
      "width": 605,
      "height": 554
    }
  ],
  "gamma-for-deck-generation-at-scale": [
    {
      "src": "/blog/gamma-for-deck-generation-at-scale-1.webp",
      "width": 625,
      "height": 625
    },
    {
      "src": "/blog/gamma-for-deck-generation-at-scale-2.webp",
      "width": 585,
      "height": 582
    }
  ],
  "gpt-4o-in-production": [
    {
      "src": "/blog/gpt-4o-in-production-1.webp",
      "width": 593,
      "height": 472
    },
    {
      "src": "/blog/gpt-4o-in-production-2.webp",
      "width": 608,
      "height": 377
    }
  ],
  "what-is-an-ai-operator": [
    {
      "src": "/blog/what-is-an-ai-operator-1.webp",
      "width": 750,
      "height": 748
    },
    {
      "src": "/blog/what-is-an-ai-operator-2.webp",
      "width": 847,
      "height": 368
    }
  ],
  "ai-medical-scribes": [
    {
      "src": "/blog/ai-medical-scribes-1.webp",
      "width": 545,
      "height": 271
    },
    {
      "src": "/blog/ai-medical-scribes-2.webp",
      "width": 794,
      "height": 795
    }
  ],
  "ai-fraud-detection-in-banking": [
    {
      "src": "/blog/ai-fraud-detection-in-banking-1.webp",
      "width": 526,
      "height": 512
    },
    {
      "src": "/blog/ai-fraud-detection-in-banking-2.webp",
      "width": 516,
      "height": 484
    }
  ],
  "ai-agent-architecture-in-production": [
    {
      "src": "/blog/ai-agent-architecture-in-production-1.webp",
      "width": 593,
      "height": 582
    },
    {
      "src": "/blog/ai-agent-architecture-in-production-2.webp",
      "width": 556,
      "height": 523
    }
  ]
};
