// Generated by tools/convert.mjs — do not edit by hand.
import type { Report } from "./types";

export const reports: Report[] = [
  {
    "id": "rp-evidence-trail",
    "series": "BFSI",
    "topic": "US Community Banking",
    "txt": "building the evidence trail the economics, governance and execution of production ai why ai programmes in u.s. community and regional banks stall after the pilot, and the sequencing that gets them into production.",
    "cover": "/img/rp-evidence-trail.webp",
    "coverAlt": "Building the Evidence Trail cover",
    "seriesLabel": "BFSI · Report 01",
    "title": "Building the Evidence Trail",
    "subtitle": "The Economics, Governance and Execution of Production AI",
    "tease": "Most banks in this bracket have run a pilot and stalled. The report traces where the stall actually happens, which is rarely the model and almost always the distance between a working demonstration and a system that can carry an audit. It sets out what the FDIC data says about who is spending and on what, why the sequencing of governance before scale is the decision that separates the two groups, and the order of operations we would follow inside a bank of that size.",
    "tags": [
      "US Community Banking",
      "FDIC-sourced"
    ],
    "name": "Building the Evidence Trail"
  },
  {
    "id": "rp-spend-without-saving",
    "series": "BFSI",
    "topic": "US Community Banking",
    "txt": "spend without the saving back-office efficiency, workflow redesign and the path to ai-driven banking why u.s. community banks are spending more on technology without seeing proportional gains in efficiency, and what has to change.",
    "cover": "/img/rp-spend-without-saving.webp",
    "coverAlt": "Spend Without the Saving cover",
    "seriesLabel": "BFSI · Report 02",
    "title": "Spend Without the Saving",
    "subtitle": "Back-Office Efficiency, Workflow Redesign and the Path to AI-Driven Banking",
    "tease": "Technology spend at U.S. community banks has risen steadily while efficiency ratios have barely moved. The report takes that gap seriously rather than treating it as a paradox: where the money goes, why back-office work absorbs it without releasing capacity, and which redesign decisions change the ratio instead of the line item. It ends on the operating changes that show up in the numbers within a reporting cycle.",
    "tags": [
      "US Community Banking",
      "Efficiency ratio"
    ],
    "name": "Spend Without the Saving"
  },
  {
    "id": "rp-line-fda-drew",
    "series": "Life Sciences",
    "topic": "Pharmacovigilance",
    "txt": "the line the fda drew pharmacovigilance, regulatory operations and manufacturing quality where pharmaceutical organisations can deploy ai today, where the fda has drawn the regulatory line, and how to move into higher-risk applications with confidence.",
    "cover": "/img/rp-line-fda-drew.webp",
    "coverAlt": "The Line the FDA Drew cover",
    "seriesLabel": "Life Sciences · Report 03",
    "title": "The Line the FDA Drew",
    "subtitle": "Pharmacovigilance, Regulatory Operations and Manufacturing Quality",
    "tease": "The FDA has been more specific about AI than most people in pharma realise, and the line it has drawn is not where the caution suggests. The report maps what can be deployed today across pharmacovigilance, regulatory operations and manufacturing quality, what the credibility framework asks of a higher-risk application, and how an organisation moves across that line with the evidence already assembled.",
    "tags": [
      "Pharmacovigilance",
      "FDA guidance"
    ],
    "name": "The Line the FDA Drew"
  },
  {
    "id": "rp-first-clinical-test",
    "series": "Life Sciences",
    "topic": "AI Drug Discovery",
    "txt": "the first clinical test ai drug discovery, clinical operations and the economics of failure what the first clinical evidence from an ai-discovered drug actually shows, what it does not, and where pharmaceutical companies should place their next ai investments.",
    "cover": "/img/rp-first-clinical-test.webp",
    "coverAlt": "The First Clinical Test cover",
    "seriesLabel": "Life Sciences · Report 04",
    "title": "The First Clinical Test",
    "subtitle": "AI Drug Discovery, Clinical Operations and the Economics of Failure",
    "tease": "An AI-discovered drug has now been through a clinical readout, and the result is more interesting than either the enthusiasts or the sceptics have reported. The report works through what the evidence actually establishes, what it does not, and what that means for where a pharmaceutical company should place its next AI investment, with the economics of failure treated as the central number rather than a footnote.",
    "tags": [
      "AI Drug Discovery",
      "Clinical evidence"
    ],
    "name": "The First Clinical Test"
  }
];

export const reportFilters = {
  "series": [
    {
      "value": "all",
      "label": "All series"
    },
    {
      "value": "BFSI",
      "label": "AI in BFSI"
    },
    {
      "value": "Life Sciences",
      "label": "Life Sciences"
    }
  ],
  "topics": [
    {
      "value": "all",
      "label": "All topics"
    },
    {
      "value": "US Community Banking",
      "label": "US Community Banking"
    },
    {
      "value": "AI Drug Discovery",
      "label": "AI Drug Discovery"
    },
    {
      "value": "Pharmacovigilance",
      "label": "Pharmacovigilance"
    }
  ]
};
