// Generated by tools/convert.mjs — do not edit by hand.
import type { ProofEntry, PanelCard } from "./types";

export const proof: Record<string, ProofEntry> = {
  "rbi": {
    "big": "~80%",
    "label": "lower grievance time",
    "big2": "~2 min",
    "label2": "to register a grievance",
    "text": "Es Magico engineered a grievance protocol that any regulated bank could adopt, one as accountable as the institutions using it. It is now live across multiple banks, and a complaint takes about two minutes to register, in eleven Indic languages. Most importantly, every grievance is logged and independently trackable.",
    "name": "Ranjeet Rane",
    "title": "Head of Research, RBI Innovation Hub",
    "lc": "logow-rbi"
  },
  "indusind": {
    "big": "50,000+",
    "label": "trained on 150+ capabilities",
    "big2": "3,000+",
    "label2": "man-hours saved",
    "text": "We needed to train more than 50,000 people across the bank on over 150 capabilities, and to be able to show exactly who had been trained on what. Es Magico gave us one standard we could actually run at that scale, and the reporting we get out of it has saved our teams thousands of hours.",
    "name": "Manish Jain",
    "title": "Vice President & Domain Head, Retail Liabilities and Internal Audit, IndusInd Bank",
    "lc": "logow-indusind"
  },
  "tata": {
    "big": "500,000+",
    "label": "users engaged",
    "big2": "700,000+",
    "label2": "rewards issued",
    "text": "The team's execution speed and ability to overcome challenges with effective solutions demonstrated strong problem-solving skills and built trust throughout the project.",
    "name": "Akash Mohan",
    "title": "VP, Tata Digital",
    "lc": "logow-tataneu2"
  },
  "isb": {
    "big": "~97%",
    "label": "concordance with faculty",
    "big2": "~80%",
    "label2": "less evaluation time",
    "text": "Thousands of applications are now screened against ISB’s own rubric before anyone reads them, so faculty interview a shortlist that is consistent, explainable and blind to the fluency bias that distorts a manual read.",
    "name": "Soumya Kumar",
    "title": "Director, iVi, Indian School of Business",
    "lc": "logow-isb"
  }
};

export const proofClients = [
  {
    "key": "rbi",
    "label": "Reserve Bank Innovation Hub",
    "logo": "logow-rbi"
  },
  {
    "key": "indusind",
    "label": "IndusInd Bank",
    "logo": "logow-indusind"
  },
  {
    "key": "tata",
    "label": "tata",
    "logo": "logow-tataneu2"
  },
  {
    "key": "isb",
    "label": "Indian School of Business",
    "logo": "logow-isb"
  }
];

export const panels: Record<string, PanelCard[]> = {
  "atlas": [
    {
      "client": "Cipla · Global Training Academy",
      "line": "SOPs turned into tracked, self-paced AI lessons for 20,000+ employees.",
      "logo": "cipla",
      "href": "/case-studies/cipla-global-training-academy/",
      "pair": [
        {
          "n": "20,000+",
          "l": "employees enabled"
        },
        {
          "n": "~70%",
          "l": "less content effort"
        }
      ]
    },
    {
      "client": "IndusInd Bank",
      "line": "Policy documents turned into 150+ AI video modules, with no trainer dependency.",
      "logo": "indusind",
      "href": "/case-studies/indusind-bank/",
      "pair": [
        {
          "n": "50,000+",
          "l": "employees trained"
        },
        {
          "n": "150+",
          "l": "AI training videos"
        }
      ]
    }
  ],
  "compass": [
    {
      "client": "Koita Foundation",
      "line": "A large body of digital-health material made answerable, traceable to source.",
      "logo": "koita",
      "href": "/case-studies/koita-foundation/",
      "pair": [
        {
          "n": "~80%",
          "l": "less information-discovery time"
        },
        {
          "n": "7+",
          "l": "repositories unified"
        }
      ]
    },
    {
      "client": "Indian School of Business · iVi",
      "line": "A candidate screen that stays consistent, explainable and blind to fluency bias.",
      "logo": "isb",
      "href": "/case-studies/indian-school-of-business/",
      "pair": [
        {
          "n": "~97%",
          "l": "concordance with faculty"
        },
        {
          "n": "~80%",
          "l": "less evaluation time"
        }
      ]
    }
  ],
  "evio": [
    {
      "client": "RBI · Innovation Hub",
      "line": "A multilingual, voice-first grievance protocol any regulated bank can adopt.",
      "logo": "rbi",
      "href": "/case-studies/rbi-innovation-hub/",
      "pair": [
        {
          "n": "~80%",
          "l": "lower grievance turnaround"
        },
        {
          "n": "~2 min",
          "l": "to register a grievance"
        }
      ]
    },
    {
      "client": "Samagra",
      "line": "Crop, weather and scheme guidance by voice, in 12 languages, no app required.",
      "logo": "samagra",
      "href": "/case-studies/samagra/",
      "pair": [
        {
          "n": "3x",
          "l": "more farmer engagement"
        },
        {
          "n": "50,000+",
          "l": "farmers engaged"
        }
      ]
    }
  ],
  "forge": [
    {
      "client": "Epic Global Inc.",
      "line": "Compliant listings generated and catalogues migrated across global marketplaces.",
      "logo": "epic",
      "href": "/case-studies/epic-global/",
      "pair": [
        {
          "n": "~65%",
          "l": "faster listing turnaround"
        },
        {
          "n": "~80%",
          "l": "fewer redundant man-hours"
        }
      ]
    },
    {
      "client": "IndiaMART",
      "line": "Voice and chat agents handling a million marketplace conversations autonomously.",
      "logo": "indiamart",
      "href": "/case-studies/indiamart/",
      "pair": [
        {
          "n": "1M+",
          "l": "conversations handled"
        },
        {
          "n": "~40%",
          "l": "lower support cost"
        }
      ]
    }
  ],
  "loupe": [
    {
      "client": "Cipla · Global Training Academy",
      "line": "SOPs turned into tracked, self-paced AI lessons for 20,000+ employees.",
      "logo": "cipla",
      "href": "/case-studies/cipla-global-training-academy/",
      "pair": [
        {
          "n": "20,000+",
          "l": "employees enabled"
        },
        {
          "n": "~70%",
          "l": "less content effort"
        }
      ]
    }
  ],
  "prism": [
    {
      "client": "Indian School of Business · iVi",
      "line": "A candidate screen that stays consistent, explainable and blind to fluency bias.",
      "logo": "isb",
      "href": "/case-studies/indian-school-of-business/",
      "pair": [
        {
          "n": "~97%",
          "l": "concordance with faculty"
        },
        {
          "n": "~80%",
          "l": "less evaluation time"
        }
      ]
    }
  ]
};

export const panelTabs = [
  {
    "key": "atlas",
    "label": "Atlas"
  },
  {
    "key": "compass",
    "label": "Compass"
  },
  {
    "key": "evio",
    "label": "Evio"
  },
  {
    "key": "forge",
    "label": "Forge"
  },
  {
    "key": "loupe",
    "label": "Loupe"
  },
  {
    "key": "prism",
    "label": "Prism"
  }
];

export const ledger = {
  "chips": [
    {
      "key": "",
      "label": "All six"
    },
    {
      "key": "Atlas",
      "label": "Atlas"
    },
    {
      "key": "Compass",
      "label": "Compass"
    },
    {
      "key": "Evio",
      "label": "Evio"
    },
    {
      "key": "Forge",
      "label": "Forge"
    },
    {
      "key": "Loupe",
      "label": "Loupe"
    },
    {
      "key": "Prism",
      "label": "Prism"
    }
  ],
  "common": 4,
  "total": 12,
  "groups": [
    {
      "title": "Reason",
      "rows": [
        {
          "n": "01",
          "title": "Orchestration & Reasoning",
          "products": [
            "Atlas",
            "Compass",
            "Evio",
            "Forge",
            "Loupe",
            "Prism"
          ]
        },
        {
          "n": "02",
          "title": "Model Layer",
          "products": [
            "Atlas",
            "Compass",
            "Evio",
            "Forge",
            "Loupe",
            "Prism"
          ]
        },
        {
          "n": "04",
          "title": "Memory & State",
          "products": [
            "Compass",
            "Evio",
            "Forge",
            "Loupe"
          ]
        }
      ]
    },
    {
      "title": "Know",
      "rows": [
        {
          "n": "03",
          "title": "Knowledge & Retrieval",
          "products": [
            "Atlas",
            "Compass",
            "Loupe",
            "Prism"
          ]
        },
        {
          "n": "07",
          "title": "Document Processing",
          "products": [
            "Atlas",
            "Compass",
            "Loupe",
            "Prism"
          ]
        },
        {
          "n": "08",
          "title": "Data & Ingestion",
          "products": [
            "Atlas",
            "Compass",
            "Forge",
            "Prism"
          ]
        }
      ]
    },
    {
      "title": "Act",
      "rows": [
        {
          "n": "09",
          "title": "Network",
          "products": [
            "Forge",
            "Loupe"
          ]
        },
        {
          "n": "10",
          "title": "Telephony & Communication",
          "products": [
            "Evio"
          ]
        },
        {
          "n": "11",
          "title": "Content & Media",
          "products": [
            "Atlas",
            "Evio",
            "Prism"
          ]
        },
        {
          "n": "12",
          "title": "Integrations & Connectors",
          "products": [
            "Compass",
            "Evio",
            "Forge",
            "Loupe"
          ]
        }
      ]
    },
    {
      "title": "Govern",
      "rows": [
        {
          "n": "05",
          "title": "Safety & Guardrails",
          "products": [
            "Atlas",
            "Compass",
            "Evio",
            "Forge",
            "Loupe",
            "Prism"
          ]
        },
        {
          "n": "06",
          "title": "Ops & Governance",
          "products": [
            "Atlas",
            "Compass",
            "Evio",
            "Forge",
            "Loupe",
            "Prism"
          ]
        }
      ]
    }
  ]
};

export const pageTitles: Record<string, string> = {
  "home": "Es Magico - The Operator for AI-native Transformation",
  "pyzo": "PYZO - Six capabilities. One hardened foundation.",
  "blogs": "The AI Operator Journal - Es Magico",
  "case-studies": "Case Studies - Es Magico",
  "reports": "Reports - Es Magico",
  "who-we-are": "About Us - Es Magico",
  "careers": "Careers - Es Magico",
  "contact": "Define an Outcome - Es Magico",
  "careers-apply": "Introduce yourself - Es Magico",
  "privacy": "Privacy Policy - Es Magico",
  "terms": "Terms & Conditions - Es Magico",
  "stack": "Technology - Es Magico",
  "pyzo-atlas": "Atlas, Training Coach - PYZO - Es Magico",
  "pyzo-compass": "Compass, Business Analyst - PYZO - Es Magico",
  "pyzo-evio": "Evio, Call Operator - PYZO - Es Magico",
  "pyzo-forge": "Forge, Workflow Executor - PYZO - Es Magico",
  "pyzo-loupe": "Loupe, Application Assistant - PYZO - Es Magico",
  "pyzo-prism": "Prism, Evaluation Consultant - PYZO - Es Magico",
  "svc-agentic": "Agentic AI - Es Magico",
  "svc-governance": "AI Governance - Es Magico",
  "svc-modernisation": "Enterprise AI - Es Magico",
  "ind-bfsi": "Banking & Financial Services - Es Magico",
  "ind-healthcare": "Healthcare & Life Sciences - Es Magico",
  "ind-public": "Public Sector & Governance - Es Magico",
  "ind-retail": "Consumer & Retail - Es Magico",
  "cs-rbi": "Grievance redressal that survives its own audit. - Case Study - Es Magico",
  "cs-cipla": "A global training academy that speaks every employee's language. - Case Study - Es Magico",
  "cs-koita": "Fragmented digital-health knowledge, made answerable in plain language. - Case Study - Es Magico",
  "cs-isb": "Thousands of applications, screened consistently and without bias. - Case Study - Es Magico",
  "cs-indusind": "Trainer-independent learning for 50,000+ employees. - Case Study - Es Magico",
  "cs-samagra": "Voice-first agricultural guidance for farmers, in their own language. - Case Study - Es Magico",
  "cs-indiamart": "A million marketplace conversations, handled autonomously. - Case Study - Es Magico",
  "cs-tataneu": "A gamified rewards engine that keeps a super-app engaged. - Case Study - Es Magico",
  "cs-epic": "Multi-marketplace e-commerce operations, automated end to end. - Case Study - Es Magico",
  "blog-human-in-the-loop-data-capture": "Human-in-the-Loop Data Capture: Where Validation Belongs in an Agentic Pipeline - Es Magico",
  "blog-measuring-ai-roi-in-banking": "Measuring AI ROI in Banking: The Cost of a Resolved Outcome - Es Magico",
  "blog-why-accountable-ai-will-outlast-generative-ai-as-the-phras": "Why ‘Accountable AI’ Will Outlast ‘Generative AI’ as the Phrase That Matters - Es Magico",
  "blog-measuring-ai-roi-in-healthcare": "Measuring AI ROI in Healthcare: Hours Returned and Outcomes Moved - Es Magico",
  "blog-latency-against-intelligence": "Latency Against Intelligence: The Trade-off That Won't Disappear - Es Magico",
  "blog-measuring-the-roi-of-ai-productivity-tools": "Measuring the ROI of AI Productivity Tools: An Operating Framework Beyond Seat Counts - Es Magico",
  "blog-the-cost-of-a-missing-field": "The Cost of a Missing Field: Engineering Complex Application Journeys That Complete - Es Magico",
  "blog-ai-client-reporting-for-asset-managers": "AI Client Reporting for Asset Managers: Automation That Stays Accurate at Scale - Es Magico",
  "blog-where-agentic-ai-is-heading-in-regulated-industries": "Where Agentic AI Is Heading in Regulated Industries: An Operator's View - Es Magico",
  "blog-the-ai-operating-model-for-health-systems": "The AI Operating Model for Health Systems: Owning the Layer That Survives Scrutiny - Es Magico",
  "blog-input-integrity-for-agentic-systems": "Input Integrity for Agentic Systems: Guiding and Validating What Humans Enter - Es Magico",
  "blog-migrating-between-foundation-models-without-rewriting-your": "Migrating Between Foundation Models Without Rewriting Your Stack - Es Magico",
  "blog-ai-design-tools-compared": "AI Design Tools Compared: Brand Control, Provenance, and Production Fit - Es Magico",
  "blog-ai-for-treasury-and-cash-flow-forecasting": "AI for Treasury and Cash-Flow Forecasting: Forecasts Finance Will Trust - Es Magico",
  "blog-latency-in-conversational-voice-ai": "Latency in Conversational Voice AI: The Trade-off That Decides Whether It Sounds Human - Es Magico",
  "blog-writing-the-anonymised-case-study": "Writing the Anonymised Case Study: Proving Outcomes Without Naming Names - Es Magico",
  "blog-responsible-ai-in-healthcare": "Responsible AI in Healthcare: From Pilot to Production Without Cutting Corners - Es Magico",
  "blog-operationalizing-multilingual-voice-agents": "Multilingual Voice Agents in Production: Quality Across 15+ Languages - Es Magico",
  "blog-multilingual-ai-customer-service-in-banking": "Multilingual AI Customer Service in Banking: Consistent Quality Across Languages - Es Magico",
  "blog-claude-opus-4-6-and-agent-teams": "Claude Opus 4.6 and Agent Teams: Putting Multi-Agent Work Into Production - Es Magico",
  "blog-the-review-debt-problem": "The Review-Debt Problem: Why AI Coding Agents Shift Cost Instead of Removing It - Es Magico",
  "blog-engineering-natural-voice-agents": "Engineering Natural Voice Agents: Turn-Taking, Speaker Separation, and Noise - Es Magico",
  "blog-scaling-outbound-conversations-without-adding-headcount": "Scaling Outbound Conversations Without Adding Headcount: A Voice AI Story - Es Magico",
  "blog-ai-in-pharma-manufacturing-and-quality": "AI in Pharma Manufacturing and Quality: GxP-Aligned Models in Production - Es Magico",
  "blog-ai-in-algorithmic-trading": "AI in Algorithmic Trading: Where Machine Learning Helps and Governance Draws the Line - Es Magico",
  "blog-designing-the-handoff": "Designing the Handoff: When a Voice Agent Should Escalate to a Person - Es Magico",
  "blog-when-should-an-enterprise-upgrade-to-a-newer-model": "When Should an Enterprise Upgrade to a Newer Model? - Es Magico",
  "blog-red-teaming-financial-ai": "Red-Teaming Financial AI: Adversarial Testing Before You Go to Production - Es Magico",
  "blog-how-a-regulated-lender-cleared-audit-on-first-pass-with-gu": "How a Regulated Lender Cleared Audit on First Pass With Guided Validation - Es Magico",
  "blog-ai-patient-facing-chatbots": "AI Patient-Facing Chatbots: Engineering Safe Answers at Scale - Es Magico",
  "blog-scaling-workforce-enablement-without-scaling-trainers": "Scaling Workforce Enablement Without Scaling Trainers - Es Magico",
  "blog-real-time-ai-avatars": "Real-Time AI Avatars: Reading Interactive Video Tools for Enterprise Use - Es Magico",
  "blog-the-economics-of-running-enterprise-ai": "The Economics of Running Enterprise AI: A Cost-Performance Operating Model - Es Magico",
  "blog-measuring-whether-training-actually-stuck": "Measuring Whether Training Actually Stuck: Assessment and Role-Play at Scale - Es Magico",
  "blog-ai-for-dispute-and-chargeback-automation": "AI for Dispute and Chargeback Automation: Faster Resolution, No Compliance Gaps - Es Magico",
  "blog-generic-ai-vs-sector-fluent-ai": "Generic AI vs Sector-Fluent AI: Why Domain Context Decides the Outcome - Es Magico",
  "blog-multimodal-ai-in-healthcare": "Multimodal AI in Healthcare: Combining Imaging, Notes, and Labs, Responsibly - Es Magico",
  "blog-onboarding-the-workforce-onto-agentic-workflows": "Onboarding the Workforce Onto Agentic Workflows: Adoption That Sticks - Es Magico",
  "blog-choosing-an-enterprise-ai-assistant-platform": "Choosing an Enterprise AI Assistant Platform: A Procurement-Grade Comparison - Es Magico",
  "blog-telematics-and-usage-based-insurance": "Telematics and Usage-Based Insurance: The Data Pipelines Behind UBI Pricing - Es Magico",
  "blog-the-frontier-bake-off": "The Frontier Bake-Off: Where the Margins Narrow and Selection Stops Mattering - Es Magico",
  "blog-ai-literacy-for-the-enterprise": "AI Literacy for the Enterprise: Knowledge Transfer at Scale - Es Magico",
  "blog-myth-a-more-powerful-model-solves-the-enterprise-ai-proble": "Myth: A More Powerful Model Solves the Enterprise AI Problem - Es Magico",
  "blog-ai-for-early-sepsis-and-deterioration-prediction": "AI for Early Sepsis and Deterioration Prediction: Acting Before the Code - Es Magico",
  "blog-ai-for-stress-testing-and-scenario-analysis": "AI for Stress Testing and Scenario Analysis: Models the Board Can Question - Es Magico",
  "blog-training-teams-to-supervise-ai-agents": "Training Teams to Supervise AI Agents: Closing the Human-Readiness Gap - Es Magico",
  "blog-claude-opus-4-5-cheaper-frontier-coding-and-what-the-price": "Claude Opus 4.5, Cheaper Frontier Coding, and What the Price Cut Signals - Es Magico",
  "blog-consolidating-the-ai-tool-stack": "Consolidating the AI Tool Stack: Cutting Sprawl Without Losing Capability - Es Magico",
  "blog-myth-a-convincing-demo-means-the-ai-is-ready": "Myth: A Convincing Demo Means the AI Is Ready - Es Magico",
  "blog-data-privacy-for-healthcare-ai": "Data Privacy for Healthcare AI: De-Identification and PHI Boundaries That Hold - Es Magico",
  "blog-ai-native-transformation": "AI-Native Transformation: Why Operating the Layer Beats Adopting the Tools - Es Magico",
  "blog-ai-in-debt-collections": "AI in Debt Collections: Improving Recovery Within Fair-Treatment Rules - Es Magico",
  "blog-incident-response-for-ai-systems": "Incident Response for AI Systems: When an Agent Does the Wrong Thing - Es Magico",
  "blog-what-a-production-ready-agent-actually-requires-most-demos": "What a Production-Ready Agent Actually Requires (Most Demos Skip Half of It) - Es Magico",
  "blog-ai-for-complaint-handling-and-conduct-risk-detection": "AI for Complaint Handling and Conduct-Risk Detection: Catching Issues Early - Es Magico",
  "blog-ai-for-regulatory-submissions-in-pharma": "AI for Regulatory Submissions in Pharma: Accelerating Filings You Can Defend - Es Magico",
  "blog-gemini-3-pro-for-multimodal-and-agentic-workloads": "Gemini 3 Pro for Multimodal and Agentic Workloads: A Production Reading - Es Magico",
  "blog-building-a-golden-dataset-for-llm-evaluation": "Building a Golden Dataset for LLM Evaluation: Your Most Valuable AI Asset - Es Magico",
  "blog-ai-audio-for-brand-content": "AI Audio for Brand Content: Adopting Music Generation Without the Licensing Trap - Es Magico",
  "blog-ai-in-portfolio-construction-and-risk-analytics": "AI in Portfolio Construction and Risk Analytics: Augmentation With Accountability - Es Magico",
  "blog-data-governance-for-agentic-ai": "Data Governance for Agentic AI: Controlling What Agents Can See and Send - Es Magico",
  "blog-buy-build-or-operate": "Buy, Build, or Operate: How Enterprises Should Source Their AI - Es Magico",
  "blog-ai-for-healthcare-fraud-waste-and-abuse-detection": "AI for Healthcare Fraud, Waste, and Abuse Detection: Defensible Flags at Scale - Es Magico",
  "blog-adaptive-reasoning-arrives": "Adaptive Reasoning Arrives: Reading GPT-5.1 Against the Field - Es Magico",
  "blog-event-driven-agent-architectures": "Event-Driven Agent Architectures: Triggering Action Without Polling - Es Magico",
  "blog-voice-ai-in-banking-call-centers": "Voice AI in Banking Call Centers: Latency, Compliance, and Escalation - Es Magico",
  "blog-voice-agents-for-the-contact-center": "Voice Agents for the Contact Centre: Latency, Compliance, and Escalation - Es Magico",
  "blog-building-an-ai-operating-model-your-risk-committee-will-ap": "Building an AI Operating Model Your Risk Committee Will Approve - Es Magico",
  "blog-ai-in-connected-medical-devices": "AI in Connected Medical Devices: Engineering Reliability at the Point of Care - Es Magico",
  "blog-an-agentic-ai-maturity-model": "An Agentic AI Maturity Model: From Pilots to Operated Fleets - Es Magico",
  "blog-selecting-a-model-for-enterprise-rag": "Selecting a Model for Enterprise RAG: A Retrieval-First Evaluation Framework - Es Magico",
  "blog-third-party-ai-risk-in-financial-services": "Third-Party AI Risk in Financial Services: Governing Vendor Models - Es Magico",
  "blog-accountability-in-autonomous-systems": "Accountability in Autonomous Systems: Who Owns the Agent's Decision - Es Magico",
  "blog-deep-document-ai-in-financial-services": "Deep Document AI in Financial Services: Evaluating Hebbia for Audit-Grade Analysis - Es Magico",
  "blog-from-proof-of-concept-to-production": "From Proof of Concept to Production: A Field Guide for Enterprise AI - Es Magico",
  "blog-ai-for-clinical-documentation-improvement": "AI for Clinical Documentation Improvement: Better Coding, Defensible Records - Es Magico",
  "blog-ai-in-health-insurance-claims-adjudication": "AI in Health Insurance Claims Adjudication: Automation Without Wrongful Denials - Es Magico",
  "blog-state-management-for-agents": "State Management for Agents: Checkpoints, Rollback, and Recovery - Es Magico",
  "blog-claude-haiku-4-5-and-the-economics-of-small-fast-models-in": "Claude Haiku 4.5 and the Economics of Small, Fast Models in Production - Es Magico",
  "blog-agreeing-the-number-before-you-start": "Agreeing the Number Before You Start: Setting AI Outcomes Leadership Will Trust - Es Magico",
  "blog-credit-model-monitoring-and-drift-detection-through-the-ec": "Credit Model Monitoring and Drift Detection Through the Economic Cycle - Es Magico",
  "blog-small-language-models-in-agentic-systems": "Small Language Models in Agentic Systems: Where Frontier Is Overkill - Es Magico",
  "blog-ai-voice-agents-in-healthcare-call-centers": "AI Voice Agents in Healthcare Call Centres: Access, Compliance, and Escalation - Es Magico",
  "blog-terminal-and-async-coding-agents-compared": "Terminal and Async Coding Agents Compared: Fitting Them Into Your Engineering Workflow - Es Magico",
  "blog-choosing-models-for-clinical-assistants": "Choosing Models for Clinical Assistants: A Healthcare Decision Guide - Es Magico",
  "blog-structured-outputs-in-production": "Structured Outputs in Production: Reliable JSON From Unreliable Models - Es Magico",
  "blog-llms-for-earnings-calls-and-filings": "LLMs for Earnings Calls and Filings: Faster Research With Verifiable Citations - Es Magico",
  "blog-the-cfo-test-for-enterprise-ai": "The CFO Test for Enterprise AI: If You Can't Measure It, It Won't Survive Scrutiny - Es Magico",
  "blog-ai-in-surgical-planning-and-intraoperative-support": "AI in Surgical Planning and Intraoperative Support: Precision With Human Control - Es Magico",
  "blog-operationalizing-ai-act-obligations": "AI Act Obligations in Practice: Engineering Compliance Into Agents - Es Magico",
  "blog-ai-in-the-tools-you-already-use": "AI in the Tools You Already Use: Reading the Permission Model Behind Claude in Excel and Chrome - Es Magico",
  "blog-ai-communications-surveillance": "AI Communications Surveillance: Monitoring Chat and Voice for Conduct Risk - Es Magico",
  "blog-claude-sonnet-4-5-and-long-horizon-agents": "Claude Sonnet 4.5 and Long-Horizon Agents: Reading the Agentic Maturity Curve - Es Magico",
  "blog-a-production-readiness-checklist-for-ai-agents": "A Production Readiness Checklist for AI Agents - Es Magico",
  "blog-demand-and-inventory-intelligence-that-performs-under-real": "Demand and Inventory Intelligence That Performs Under Real Margins - Es Magico",
  "blog-monitoring-clinical-ai-in-production": "Monitoring Clinical AI in Production: Catching Drift Before Patients Feel It - Es Magico",
  "blog-ai-in-mortgage-processing": "AI in Mortgage Processing: Document Automation Across Origination - Es Magico",
  "blog-failure-analysis-for-ai-agents": "Failure Analysis for AI Agents: Turning Production Errors Into Eval Cases - Es Magico",
  "blog-the-best-models-for-ai-agents": "The Best Models for AI Agents: An Agentic-Readiness Selection Framework - Es Magico",
  "blog-order-delivery-and-returns-calls": "Order, Delivery and Returns Calls: Voice AI for Retail Operations - Es Magico",
  "blog-ai-nursing-assistants-and-workflow-support": "AI Nursing Assistants and Workflow Support: Easing Load Without Adding Risk - Es Magico",
  "blog-knowledge-graphs-and-rag": "Knowledge Graphs and RAG: When Structure Beats Pure Vector Search - Es Magico",
  "blog-notion-s-workspace-agents": "Notion's Workspace Agents: AI Inside the Tools You Already Operate - Es Magico",
  "blog-next-best-action-for-relationship-managers": "Next-Best-Action for Relationship Managers: AI Guidance Bankers Actually Trust - Es Magico",
  "blog-the-supervisor-pattern-for-multi-agent-systems": "The Supervisor Pattern for Multi-Agent Systems: Coordination You Can Govern - Es Magico",
  "blog-claude-opus-4-1-for-enterprise-coding": "Claude Opus 4.1 for Enterprise Coding: Where It Earns Its Cost - Es Magico",
  "blog-personalisation-that-holds-up-at-scale": "Personalisation That Holds Up at Scale: Retail AI Beyond the Pilot - Es Magico",
  "blog-ai-in-genomics-and-variant-interpretation": "AI in Genomics and Variant Interpretation: Scaling Analysis With Accountability - Es Magico",
  "blog-accelerated-life-insurance-underwriting-with-ai": "Accelerated Life Insurance Underwriting With AI: Speed Without Anti-Selection - Es Magico",
  "blog-excessive-agency": "Excessive Agency: The Agent Security Risk Permissions Quietly Create - Es Magico",
  "blog-when-anyone-can-generate-an-app": "When Anyone Can Generate an App: Managing the Citizen-Development and Shadow-IT Risk - Es Magico",
  "blog-explainable-fraud-detection": "Explainable Fraud Detection: Decisions You Can Defend to Customers and Regulators - Es Magico",
  "blog-agents-vs-workflow-automation": "Agents vs Workflow Automation: Choosing the Right Tool for the Job - Es Magico",
  "blog-preserving-institutional-knowledge-in-government-with-agen": "Preserving Institutional Knowledge in Government With Agentic AI - Es Magico",
  "blog-ai-for-medical-record-summarization": "AI for Medical Record Summarisation: Faster Chart Review You Can Trust - Es Magico",
  "blog-are-frontier-models-becoming-commodities-an-operator-s-vie": "Are Frontier Models Becoming Commodities? An Operator's View on Differentiation - Es Magico",
  "blog-measuring-agent-roi": "Measuring Agent ROI: What One Resolved Task Actually Costs - Es Magico",
  "blog-data-privacy-and-residency-for-ai-in-banking": "Data Privacy and Residency for AI in Banking: Engineer the Boundaries First - Es Magico",
  "blog-customer-support-agents-compared": "Customer-Support Agents Compared: Deflection, Escalation, and Accountability - Es Magico",
  "blog-ai-for-accreditation-and-citizen-services": "AI for Accreditation and Citizen Services: Procedural Rigour by Design - Es Magico",
  "blog-ai-in-mental-health-support": "AI in Mental Health Support: Where It Helps and Where the Guardrails Must Hold - Es Magico",
  "blog-an-ai-risk-management-framework-for-agentic-systems": "An AI Risk Management Framework for Agentic Systems - Es Magico",
  "blog-gpt-5-in-production": "GPT-5 in Production: Deploying a Unified, Routed Model - Es Magico",
  "blog-geospatial-ai-for-catastrophe-and-property-risk": "Geospatial AI for Catastrophe and Property Risk: Better Exposure Models - Es Magico",
  "blog-durable-execution-for-long-running-agents": "Durable Execution for Long-Running Agents: Reliability Infrastructure That Holds - Es Magico",
  "blog-fair-and-auditable": "Fair and Auditable: What Public-Sector AI Has to Prove - Es Magico",
  "blog-on-prem-vs-cloud-ai-for-hospitals": "On-Prem vs Cloud AI for Hospitals: A PHI-First Deployment Decision Guide - Es Magico",
  "blog-agentic-browsers-in-the-enterprise": "Agentic Browsers in the Enterprise: Reading the Security Surface of AI That Clicks - Es Magico",
  "blog-explainable-credit-decisions": "Explainable Credit Decisions: Generating Adverse-Action Notices From AI Models - Es Magico",
  "blog-continuous-evaluation-pipelines": "Continuous Evaluation Pipelines: Catching Regression Before Your Users Do - Es Magico",
  "blog-function-calling-and-tool-use-compared": "Function Calling and Tool Use, Compared: Where Model Maturity Actually Differs - Es Magico",
  "blog-handling-sensitive-health-data": "Handling Sensitive Health Data: Engineering AI for Privacy and Trust - Es Magico",
  "blog-operating-mcp-servers-in-the-enterprise": "Operating MCP Servers in the Enterprise: Governance for Standardised Tool Access - Es Magico",
  "blog-ai-in-the-ehr-reducing-click-burden-without-compromising-t": "AI in the EHR: Reducing Click Burden Without Compromising the Record - Es Magico",
  "blog-ai-for-esg-data-extraction-and-scoring": "AI for ESG Data Extraction and Scoring: Defensible Sustainability Signals - Es Magico",
  "blog-chatgpt-agent-examined": "ChatGPT Agent, Examined: A Unified Agent and the Oversight It Demands - Es Magico",
  "blog-scaling-agents-across-the-enterprise": "Scaling Agents Across the Enterprise: From One Workflow to a Fleet - Es Magico",
  "blog-kimi-k2-and-open-agentic-models": "Kimi K2 and Open Agentic Models: Evaluating Moonshot AI for Tool-Heavy Workloads - Es Magico",
  "blog-ai-for-regulatory-change-management": "AI for Regulatory Change Management: From Obligation to Operational Control - Es Magico",
  "blog-patient-reminder-and-scheduling-calls": "Patient Reminder and Scheduling Calls: Voice AI That Reduces No-Shows - Es Magico",
  "blog-validating-medical-imaging-ai": "Validating Medical Imaging AI: Why Test-Set Performance Isn't Clinical Readiness - Es Magico",
  "blog-agentic-design-patterns": "Agentic Design Patterns: A Practitioner's Catalogue for Production Systems - Es Magico",
  "blog-grok-4-for-the-enterprise": "Grok 4 for the Enterprise: Capability, Governance, and the Cost of a New Default - Es Magico",
  "blog-authorized-push-payment-scam-detection": "Authorized Push Payment Scam Detection: Real-Time Intervention That Works - Es Magico",
  "blog-approval-workflows-for-autonomous-agents": "Approval Workflows for Autonomous Agents: Designing the Pause Before the Action - Es Magico",
  "blog-meeting-intelligence-tools-in-the-enterprise": "Meeting Intelligence Tools in the Enterprise: Value Against Privacy and Retention Risk - Es Magico",
  "blog-cutting-administrative-load-in-healthcare-without-cutting": "Cutting Administrative Load in Healthcare Without Cutting Corners on Safety - Es Magico",
  "blog-ai-in-oncology-from-tumor-detection-to-treatment-planning": "AI in Oncology: From Tumour Detection to Treatment Planning, With Oversight - Es Magico",
  "blog-monitoring-llms-in-production": "Monitoring LLMs in Production: Catching Drift, Degradation, and Silent Failures - Es Magico",
  "blog-the-ai-operating-model-for-banks": "The AI Operating Model for Banks: Why Owning the Operating Layer Wins - Es Magico",
  "blog-why-small-models-often-win-in-production": "Why Small Models Often Win in Production: A Frontier-vs-Small Trade-off Analysis - Es Magico",
  "blog-clinical-decision-support-that-keeps-the-clinician-in-the": "Clinical Decision Support That Keeps the Clinician in the Loop - Es Magico",
  "blog-inference-optimization-for-llm-workloads": "Inference Optimisation for LLM Workloads: Throughput, Batching, and Cost - Es Magico",
  "blog-explainable-ai-in-diagnosis": "Explainable AI in Diagnosis: Decisions Clinicians and Regulators Can Question - Es Magico",
  "blog-ai-workflow-automation-compared": "AI Workflow Automation Compared: Governing What You Automate - Es Magico",
  "blog-ai-policy-servicing-agents-in-insurance": "AI Policy-Servicing Agents in Insurance: Self-Service Without Mis-Selling - Es Magico",
  "blog-long-term-memory-for-agents": "Long-Term Memory for Agents: Retrieval, Decay, and Avoiding Context Pollution - Es Magico",
  "blog-which-foundation-model-should-a-bank-standardize-on": "Which Foundation Model Should a Bank Standardise On? - Es Magico",
  "blog-fraud-flags-you-can-explain": "Fraud Flags You Can Explain: Accountable AI for Financial Services - Es Magico",
  "blog-ai-in-population-health": "AI in Population Health: Risk Stratification That Targets the Right Patients - Es Magico",
  "blog-fair-lending-compliance-for-ai-credit-models": "Fair-Lending Compliance for AI Credit Models: Bias Testing You Can Defend - Es Magico",
  "blog-reducing-hallucinations-in-agentic-systems": "Reducing Hallucinations in Agentic Systems: Constraints That Actually Hold - Es Magico",
  "blog-gamma-against-canva-for-ai-generated-decks-and-design": "Gamma Against Canva for AI-Generated Decks and Design: A Decision Guide - Es Magico",
  "blog-red-teaming-ai-agents": "Red-Teaming AI Agents: Adversarial Testing Before You Go Live - Es Magico",
  "blog-on-prem-vs-cloud-llms-for-banks": "On-Prem vs Cloud LLMs for Banks: A Deployment Decision Guide - Es Magico",
  "blog-compliant-collections-calls-at-scale": "Compliant Collections Calls at Scale: What Voice AI Has to Get Right in BFSI - Es Magico",
  "blog-choosing-an-ai-model-for-clinical-assistants": "Choosing an AI Model for Clinical Assistants: A Healthcare Decision Guide - Es Magico",
  "blog-llama-4-against-qwen-3-for-private-and-sovereign-enterpris": "Llama 4 Against Qwen 3 for Private and Sovereign Enterprise Deployment - Es Magico",
  "blog-hybrid-search-for-enterprise-rag": "Hybrid Search for Enterprise RAG: Why Semantic Alone Isn't Enough - Es Magico",
  "blog-ai-in-actuarial-modeling": "AI in Actuarial Modeling: Where It Helps and Where Judgment Stays Human - Es Magico",
  "blog-coding-assistants-compared": "Coding Assistants Compared: A Production Selection Guide for Engineering Teams - Es Magico",
  "blog-automating-loan-document-checks-without-breaking-your-audi": "Automating Loan Document Checks Without Breaking Your Audit Trail - Es Magico",
  "blog-planning-in-ai-agents": "Planning in AI Agents: Decomposition, Re-Planning, and Where It Goes Wrong - Es Magico",
  "blog-ai-in-remote-patient-monitoring": "AI in Remote Patient Monitoring: Turning Sensor Data Into Action - Es Magico",
  "blog-claude-4-and-sustained-agentic-work": "Claude 4 and Sustained Agentic Work: What Long-Horizon Tasks Demand of an Operator - Es Magico",
  "blog-account-takeover-prevention": "Account Takeover Prevention: Behavioral Biometrics in Digital Banking - Es Magico",
  "blog-operationalizing-responsible-ai": "Responsible AI in Practice: From Principles to Enforced Controls - Es Magico",
  "blog-ai-underwriting-that-survives-a-model-risk-committee": "AI Underwriting That Survives a Model-Risk Committee - Es Magico",
  "blog-ai-in-pharmacovigilance": "AI in Pharmacovigilance: Adverse-Event Detection at Scale - Es Magico",
  "blog-ai-image-generation-for-brand-creative": "AI Image Generation for Brand Creative: A Governance-First Adoption Guide - Es Magico",
  "blog-why-ai-benchmarks-don-t-predict-production-performance": "Why AI Benchmarks Don't Predict Production Performance - Es Magico",
  "blog-controlling-ai-hallucinations-in-financial-advice": "Controlling AI Hallucinations in Financial Advice: Constraints That Hold - Es Magico",
  "blog-the-best-coding-models-for-software-teams": "The Best Coding Models for Software Teams: A Production Selection Guide - Es Magico",
  "blog-prompt-caching-in-production": "Prompt Caching in Production: Cutting Cost and Latency Without Quality Loss - Es Magico",
  "blog-the-es-magico-product-suite": "The Es Magico Product Suite: How the Agentic Capabilities Fit Together - Es Magico",
  "blog-ai-in-the-radiology-workflow": "AI in the Radiology Workflow: Worklist Prioritisation That Earns Radiologist Trust - Es Magico",
  "blog-ai-trade-surveillance": "AI Trade Surveillance: Detecting Market Abuse Without Drowning in Alerts - Es Magico",
  "blog-reasoning-tiers-compared": "Reasoning Tiers Compared: o3, o4-mini, and Choosing Depth Against Cost - Es Magico",
  "blog-build-or-buy-your-agent-stack": "Build or Buy Your Agent Stack: A Control-and-Velocity Decision Lens - Es Magico",
  "blog-generative-video-in-marketing": "Generative Video in Marketing: Deploying Runway Without the Rights Risk - Es Magico",
  "blog-ai-for-loan-default-prediction": "AI for Loan Default Prediction: Early-Warning Systems That Prioritize Collections - Es Magico",
  "blog-loupe-explained": "LOUPE, Explained: Guided Form-Filling for High-Stakes Submissions - Es Magico",
  "blog-ci-cd-for-llm-applications": "CI/CD for LLM Applications: Shipping Changes Without Breaking Production - Es Magico",
  "blog-controlling-hallucinations-in-medical-ai": "Controlling Hallucinations in Medical AI: Grounding Every Clinical Claim - Es Magico",
  "blog-llama-4-mixture-of-experts-and-sovereign-deployment": "Llama 4, Mixture-of-Experts, and Sovereign Deployment: Reading the Open-Weight Shift - Es Magico",
  "blog-multi-agent-communication": "Multi-Agent Communication: Shared State, Message Passing, and Where It Deadlocks - Es Magico",
  "blog-ai-for-investment-research": "AI for Investment Research: Faster Analyst Summaries You Can Audit - Es Magico",
  "blog-genspark-s-multi-agent-approach": "Genspark's Multi-Agent Approach: Where Orchestrated Agents Fit Enterprise Workflows - Es Magico",
  "blog-compass-explained": "COMPASS, Explained: Making Institutional Knowledge Answerable - Es Magico",
  "blog-ai-for-clinical-trial-patient-matching": "AI for Clinical Trial Patient Matching: Faster Enrolment, Cleaner Eligibility - Es Magico",
  "blog-testing-ai-agents": "Testing AI Agents: Why Unit Tests Don't Cover Non-Deterministic Systems - Es Magico",
  "blog-ai-in-sme-lending": "AI in SME Lending: Automating Document-Heavy Underwriting at Speed - Es Magico",
  "blog-gemini-against-claude-for-document-intelligence": "Gemini Against Claude for Document Intelligence: A Long-Context Decision Guide - Es Magico",
  "blog-audit-trails-for-autonomous-agents": "Audit Trails for Autonomous Agents: Logging Decisions Regulators Will Question - Es Magico",
  "blog-prism-explained": "PRISM, Explained: Defensible Evaluation at Enterprise Scale - Es Magico",
  "blog-bias-in-healthcare-ai": "Bias in Healthcare AI: Detecting and Defending Against Inequitable Models - Es Magico",
  "blog-manus-and-the-autonomous-agent-promise": "Manus and the Autonomous Agent Promise: Separating Capability From Production Reality - Es Magico",
  "blog-graph-ai-for-money-laundering-detection": "Graph AI for Money Laundering Detection: Finding the Network - Es Magico",
  "blog-sandboxing-agent-generated-code": "Sandboxing Agent-Generated Code: Containing What You Can't Fully Trust - Es Magico",
  "blog-long-context-reasoning-in-production": "Long-Context Reasoning in Production: Deploying Gemini 2.5 Pro - Es Magico",
  "blog-atlas-explained": "ATLAS, Explained: Turning SOPs Into On-Demand Learning That Sticks - Es Magico",
  "blog-ai-for-patient-engagement-and-follow-up": "AI for Patient Engagement and Follow-Up: Adherence Without Eroding Trust - Es Magico",
  "blog-agent-interoperability-and-the-a2a-protocol": "Agent Interoperability and the A2A Protocol: Reading Cross-Vendor Standards - Es Magico",
  "blog-explainable-ai-in-finance": "Explainable AI in Finance: Choosing Methods That Satisfy Regulators - Es Magico",
  "blog-domain-ai-for-legal-work": "Domain AI for Legal Work: Reading Harvey Through a Governance Lens - Es Magico",
  "blog-function-calling-maturity": "Function Calling Maturity: Where Models Differ and Why It Breaks Agents - Es Magico",
  "blog-intelligent-document-processing-in-insurance": "Intelligent Document Processing in Insurance: The Engine Behind Claims Automation - Es Magico",
  "blog-evio-explained": "EVIO, Explained: Voice AI That Sounds Human and Holds Up Under Compliance - Es Magico",
  "blog-generative-ai-in-healthcare": "Generative AI in Healthcare: Where It's Production-Ready and Where It Isn't - Es Magico",
  "blog-why-benchmark-scores-don-t-survive-contact-with-production": "Why Benchmark Scores Don't Survive Contact With Production - Es Magico",
  "blog-the-react-pattern-in-production": "The ReAct Pattern in Production: Reasoning and Acting Without Runaway Loops - Es Magico",
  "blog-perpetual-kyc-continuous-risk-monitoring-without-drowning": "Perpetual KYC: Continuous Risk Monitoring Without Drowning in Reviews - Es Magico",
  "blog-automated-research-tools-in-production": "Automated Research Tools in Production: Speed Versus Verifiable Truth - Es Magico",
  "blog-llm-as-a-judge-where-automated-evaluation-works-and-where": "LLM-as-a-Judge: Where Automated Evaluation Works and Where It Lies - Es Magico",
  "blog-multimodal-multilingual-ai": "Multimodal, Multilingual AI: Engineering Consistency Across Channels - Es Magico",
  "blog-ai-for-claims-denial-management": "AI for Claims Denial Management: Predicting and Preventing Payer Rejections - Es Magico",
  "blog-grok-3-and-a-crowded-frontier": "Grok 3 and a Crowded Frontier: Reading a New Entrant for Enterprise Use - Es Magico",
  "blog-the-real-cost-of-running-ai-agents": "The Real Cost of Running AI Agents: Token Economics at Production Scale - Es Magico",
  "blog-ai-personalization-in-banking": "AI Personalization in Banking: Relevant Offers Within Consent and Conduct Rules - Es Magico",
  "blog-getting-rag-to-hold-up-in-a-regulated-enterprise": "Getting RAG to Hold Up in a Regulated Enterprise - Es Magico",
  "blog-ai-in-digital-pathology": "AI in Digital Pathology: Augmenting the Pathologist - Es Magico",
  "blog-securing-agentic-systems": "Securing Agentic Systems: The Threat Model Beyond Prompt Injection - Es Magico",
  "blog-controllable-thinking": "Controllable Thinking: Deploying Claude 3.7 Sonnet's Hybrid Reasoning - Es Magico",
  "blog-glean-and-permissions-aware-enterprise-search": "Glean and Permissions-Aware Enterprise Search: Knowledge Work in Production - Es Magico",
  "blog-dora-and-ai-in-finance": "DORA and AI in Finance: Operational Resilience for Production AI Systems - Es Magico",
  "blog-context-engineering": "Context Engineering: Managing the Window as a Production Resource - Es Magico",
  "blog-agentic-workflows-vs-chatbots-and-rpa": "Agentic Workflows vs Chatbots and RPA: What's Actually Different - Es Magico",
  "blog-ai-for-patient-scheduling-and-no-show-reduction": "AI for Patient Scheduling and No-Show Reduction: Operational Gains That Hold Up - Es Magico",
  "blog-synthetic-identity-fraud": "Synthetic Identity Fraud: Detecting Customers Who Don't Actually Exist - Es Magico",
  "blog-measuring-rag-quality": "Measuring RAG Quality: Grounding, Faithfulness, and Retrieval Metrics - Es Magico",
  "blog-is-open-source-catching-up-deepseek-against-gpt-and-claude": "Is Open Source Catching Up? DeepSeek Against GPT and Claude in Enterprise Conditions - Es Magico",
  "blog-synthesia-against-heygen-for-enterprise-video-at-scale": "Synthesia Against HeyGen for Enterprise Video at Scale - Es Magico",
  "blog-ai-for-regulatory-reporting-and-reconciliation": "AI for Regulatory Reporting and Reconciliation: Accuracy You Can Defend - Es Magico",
  "blog-why-most-enterprise-agent-pilots-never-reach-production": "Why Most Enterprise Agent Pilots Never Reach Production - Es Magico",
  "blog-human-in-the-loop-that-survives-scrutiny": "Human-in-the-Loop That Survives Scrutiny: Oversight That Actually Works - Es Magico",
  "blog-fda-regulated-ai": "FDA-Regulated AI: What SaMD Approval Means for Your Clinical Model - Es Magico",
  "blog-deepseek-r1-and-open-reasoning": "DeepSeek R1 and Open Reasoning: What Transparent Chains of Thought Mean for Governance - Es Magico",
  "blog-agent-observability": "Agent Observability: Tracing Decisions You Have to Answer For - Es Magico",
  "blog-insurance-fraud-detection-with-ai": "Insurance Fraud Detection With AI: Catching Fraud Without Punishing Honest Claimants - Es Magico",
  "blog-explainability-by-design": "Explainability by Design: Making Every AI Decision Defensible to an Auditor - Es Magico",
  "blog-ai-medical-coding-and-autocoding": "AI Medical Coding and Autocoding: Accuracy You Can Defend in an Audit - Es Magico",
  "blog-elevenlabs-and-production-voice": "ElevenLabs and Production Voice: Quality, Latency, and the Fraud Surface - Es Magico",
  "blog-engineering-guardrails-for-ai-agents": "Engineering Guardrails for AI Agents: Input, Output, and Action Controls - Es Magico",
  "blog-rag-for-banking-knowledge-bases": "RAG for Banking Knowledge Bases: Building Policy Assistants You Can Trust - Es Magico",
  "blog-deepseek-v3-and-the-cost-shock": "DeepSeek-V3 and the Cost Shock: When Efficient Open Weights Change the Math - Es Magico",
  "blog-error-handling-for-ai-agents": "Error Handling for AI Agents: Recovering From Bad Tool Output and Dead Ends - Es Magico",
  "blog-designing-governance-into-agentic-ai-not-bolting-it-on": "Designing Governance Into Agentic AI From the First Sprint - Es Magico",
  "blog-rag-for-clinical-knowledge": "RAG for Clinical Knowledge: Building Guideline Assistants Clinicians Can Trust - Es Magico",
  "blog-app-generation-tools-compared": "App-Generation Tools Compared: From Generated UI to a System You Can Operate - Es Magico",
  "blog-designing-agentic-workflows": "Designing Agentic Workflows: Where Determinism Beats Autonomy - Es Magico",
  "blog-alternative-data-credit-scoring": "Alternative-Data Credit Scoring: Expanding Access Without Importing Bias - Es Magico",
  "blog-gemini-2-0-flash-and-the-economics-of-an-agentic-multimoda": "Gemini 2.0 Flash and the Economics of an Agentic, Multimodal Default - Es Magico",
  "blog-what-hardened-means-in-enterprise-ai-and-how-reusable-bloc": "What ‘Hardened’ Means in Enterprise AI, and How Reusable Blocks Inherit Trust - Es Magico",
  "blog-ai-in-drug-discovery": "AI in Drug Discovery: Where It Compresses Timelines and Where Validation Stays Hard - Es Magico",
  "blog-the-model-context-protocol": "The Model Context Protocol: Standardising Tool Access, and What It Costs - Es Magico",
  "blog-ai-sanctions-screening": "AI Sanctions Screening: Better Name Matching With a Defensible Audit Trail - Es Magico",
  "blog-microsoft-365-copilot-in-production": "Microsoft 365 Copilot in Production: The Permissions Problem Nobody Demos - Es Magico",
  "blog-building-an-llm-evaluation-framework-your-team-will-actual": "Building an LLM Evaluation Framework Your Team Will Actually Use - Es Magico",
  "blog-the-architecture-behind-our-platform": "The Architecture Behind Our Platform: Reusable Building Blocks for Enterprise Agents - Es Magico",
  "blog-ai-in-revenue-cycle-management": "AI in Revenue Cycle Management: Cleaner Claims, Fewer Denials - Es Magico",
  "blog-agent-assist-for-banking-contact-centers": "Agent Assist for Banking Contact Centers: Augmenting Bankers Without Adding Risk - Es Magico",
  "blog-from-preview-to-production": "From Preview to Production: o1-Class Reasoning at Real Cost - Es Magico",
  "blog-deploying-ai-agents-at-scale": "Deploying AI Agents at Scale: The Runtime Layer That Decides Reliability - Es Magico",
  "blog-ai-underwriting-in-p-c-insurance": "AI Underwriting in P&C Insurance: Pricing Accuracy Against Fairness - Es Magico",
  "blog-multi-agent-systems": "Multi-Agent Systems: When Coordination Earns Its Complexity - Es Magico",
  "blog-the-operating-principles-behind-every-es-magico-engagement": "The Operating Principles Behind Every Es Magico Engagement - Es Magico",
  "blog-hipaa-compliant-ai": "HIPAA-Compliant AI: Engineering PHI Boundaries Before You Deploy - Es Magico",
  "blog-heygen-and-synthetic-video": "HeyGen and Synthetic Video: AI Avatars for Training and Comms - Es Magico",
  "blog-open-or-closed-a-practitioner-s-framework-for-choosing-fou": "Open or Closed: A Practitioner's Framework for Choosing Foundation Models in the Enterprise - Es Magico",
  "blog-defending-agents-against-prompt-injection": "Defending Agents Against Prompt Injection: An Architecture Problem - Es Magico",
  "blog-model-risk-management-for-generative-ai": "Model Risk Management for Generative AI: Extending SR 11-7 to LLMs - Es Magico",
  "blog-ai-native-vs-ai-first": "AI-native vs AI-first: What the Distinction Means for Your Enterprise - Es Magico",
  "blog-ai-symptom-checkers-and-triage-chatbots": "AI Symptom Checkers and Triage Chatbots: Safe Routing Under Clinical Rules - Es Magico",
  "blog-llm-cost-optimization": "LLM Cost Optimisation: The Levers Operators Underuse - Es Magico",
  "blog-context-windows-explained-for-operators": "Context Windows, Explained for Operators: Where Long Context Helps and Where It Quietly Fails - Es Magico",
  "blog-agentforce-examined": "Agentforce, Examined: What CRM-Native Agents Change About Customer Operations - Es Magico",
  "blog-robo-advisors-and-ai-in-wealth-management": "Robo-Advisors and AI in Wealth Management: Automating Advice Within Suitability Rules - Es Magico",
  "blog-llmops-in-practice": "LLMOps in Practice: The Operational Layer Between a Model and Production - Es Magico",
  "blog-why-enterprises-choose-es-magico-to-run-ai-in-regulated-en": "Why Enterprises Choose Es Magico to Operate AI in Regulated Environments - Es Magico",
  "blog-ambient-clinical-documentation": "Ambient Clinical Documentation: From Conversation to Audit-Ready Note - Es Magico",
  "blog-ai-in-insurance-claims-processing": "AI in Insurance Claims Processing: From FNOL to Settlement, Safely - Es Magico",
  "blog-agent-memory-systems": "Agent Memory Systems: Engineering State Without Losing Control - Es Magico",
  "blog-computer-use-is-here-but-agentic-readiness-isn-t": "Computer Use Is Here, But Agentic Readiness Isn't: Reading the Claude 3.5 Sonnet Update - Es Magico",
  "blog-cursor-in-the-enterprise": "Cursor in the Enterprise: An AI Code Editor's Real Production Trade-offs - Es Magico",
  "blog-agentic-rag-when-retrieval-becomes-a-decision-not-a-lookup": "Agentic RAG: When Retrieval Becomes a Decision - Es Magico",
  "blog-inside-es-magico": "Inside Es Magico: The Operator for AI-native Transformation - Es Magico",
  "blog-ai-for-prior-authorization": "AI for Prior Authorisation: Speeding Approvals Without Wrongful Denials - Es Magico",
  "blog-aml-transaction-monitoring-with-ai": "AML Transaction Monitoring With AI: Fewer Alerts, Never a Missed Filing - Es Magico",
  "blog-qwen2-5-for-regulated-workloads": "Qwen2.5 for Regulated Workloads: Evaluating Open Weights From Alibaba - Es Magico",
  "blog-human-in-the-loop-design": "Human-in-the-Loop Design: Where to Put the Human and Where Not To - Es Magico",
  "blog-ai-in-kyc-and-customer-onboarding": "AI in KYC and Customer Onboarding: Faster Verification Without the False Rejects - Es Magico",
  "blog-why-most-enterprise-ai-stalls-after-the-pilot-and-what-ope": "Why Most Enterprise AI Stalls After the Pilot, and What Operators Do Differently - Es Magico",
  "blog-clinical-decision-support-with-ai": "Clinical Decision Support With AI: Augmenting Diagnosis Without Overriding Judgment - Es Magico",
  "blog-governing-agentic-ai": "Governing Agentic AI: Oversight as a Load-Bearing System - Es Magico",
  "blog-notebooklm-and-source-grounded-ai": "NotebookLM and Source-Grounded AI: When Constraining the Model Is the Feature - Es Magico",
  "blog-reasoning-models-reach-the-enterprise": "Reasoning Models Reach the Enterprise: What o1-Preview Changes About AI System Design - Es Magico",
  "blog-ai-credit-scoring-and-underwriting": "AI Credit Scoring and Underwriting: The Explainability Burden on Every Decision - Es Magico",
  "blog-evaluating-ai-agents": "Evaluating AI Agents: Why Task Success Rate Is the Only Metric That Matters - Es Magico",
  "blog-deploying-ai-is-easy-operationalising-it-is-the-work": "Deploying AI Is Easy. Operationalising It Is the Work. - Es Magico",
  "blog-ai-governance-in-healthcare": "AI Governance in Healthcare: A Practical Framework for Clinical Deployment - Es Magico",
  "blog-llm-tool-calling-in-production": "LLM Tool Calling in Production: Schema Adherence, Retries, and Recovery - Es Magico",
  "blog-perplexity-as-an-enterprise-answer-engine": "Perplexity as an Enterprise Answer Engine: Citations, Trust, and Data Exposure - Es Magico",
  "blog-ai-governance-in-financial-services": "AI Governance in Financial Services: A Practical Framework for Banks - Es Magico",
  "blog-llama-3-1-405b-and-the-case-for-open-weight-models-in-regu": "Llama 3.1 405B and the Case for Open-Weight Models in Regulated Deployments - Es Magico",
  "blog-agent-orchestration-patterns": "Agent Orchestration Patterns: Sequential, Parallel, and When to Use Each - Es Magico",
  "blog-consultant-integrator-or-operator": "Consultant, Integrator, or Operator: Who Actually Owns Your AI in Production - Es Magico",
  "blog-ai-in-medical-imaging": "AI in Medical Imaging: Where Diagnostic Support Helps and Where Radiologists Stay in the Loop - Es Magico",
  "blog-ai-chatbots-in-banking": "AI Chatbots in Banking: What Separates a Production Assistant From a Demo - Es Magico",
  "blog-why-ai-agents-fail-in-production": "Why AI Agents Fail in Production: The Failure Modes Nobody Demos - Es Magico",
  "blog-gamma-for-deck-generation-at-scale": "Gamma for Deck Generation at Scale: Where AI Presentations Earn Their Place - Es Magico",
  "blog-gpt-4o-in-production": "GPT-4o in Production: Multimodal Workflows Without the Glue Code - Es Magico",
  "blog-what-is-an-ai-operator-the-category-built-for-the-work-aft": "What Is an AI Operator? The Category Built for the Work After the Demo - Es Magico",
  "blog-ai-medical-scribes": "AI Medical Scribes: Cutting Clinician Documentation Burden Without Adding Risk - Es Magico",
  "blog-ai-fraud-detection-in-banking": "AI Fraud Detection in Banking: Scoring Inside the Authorization Window - Es Magico",
  "blog-ai-agent-architecture-in-production": "AI Agent Architecture in Production: Patterns That Survive Real Workloads - Es Magico"
};
