/*
 * Blog image pipeline.
 *
 *   node --experimental-strip-types tools/images.mjs
 *
 * Reads the client's export at tools/src/blog-src/Blogs Complete/<Category>/#N/*.png,
 * where #N is the post's position in the journal (N = 325 is the newest; the site's
 * own numbering, verified against the 231 posts that already referenced N-1.webp).
 * Each PNG is converted to WebP, never upscaled, capped at MAX_WIDTH, and written to
 * public/blog/<post-slug>-<index>.webp. Dimensions are recorded in data/blog-images.ts
 * for the converter, which places them back into the article body and the cards.
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC = path.join(ROOT, "tools/src/blog-src/Blogs Complete");
const OUT = path.join(ROOT, "public/blog");
const MAX_WIDTH = 1200; // the article column is 74ch (~700px); 1200 leaves 2x headroom for next/image
const QUALITY = 82;

const { blogCards } = await import("../data/blog-index.ts");
const slugByN = new Map(blogCards.map((c) => [324 - c.ts, c.slug]));

/* Two folders in the export are numbered #308. The one under "AI in BFSI" holds
   "Aggregate Scores Can Hide What Matters Most", which is the section
   "The aggregate score that hid two failing languages" of post #307 (tagged AI in
   BFSI, and otherwise without a folder). Reassigned explicitly; see docs/seo-open-items.md. */
const OVERRIDES = { "AI in BFSI/#308": 307 };

// folder #N -> its PNGs in order (1.png, 2.png / screenshot timestamps sort naturally)
const folders = new Map();
for (const cat of fs.readdirSync(SRC)) {
  const catDir = path.join(SRC, cat);
  if (!fs.statSync(catDir).isDirectory()) continue;
  for (const f of fs.readdirSync(catDir)) {
    const m = f.match(/^#(\d+)$/);
    if (!m) continue;
    const n = OVERRIDES[`${cat}/${f}`] ?? Number(m[1]);
    const files = fs
      .readdirSync(path.join(catDir, f))
      .filter((x) => /\.png$/i.test(x))
      .sort((a, b) => a.localeCompare(b, "en", { numeric: true }))
      .map((x) => path.join(catDir, f, x));
    if (folders.has(n)) throw new Error(`folder #${n} appears twice: ${cat} and ${folders.get(n).cat}`);
    folders.set(n, { cat, files });
  }
}

fs.mkdirSync(OUT, { recursive: true });
// the folder is rebuilt from scratch so nothing stale survives a rename
for (const f of fs.readdirSync(OUT)) fs.unlinkSync(path.join(OUT, f));

const images = {};
const missing = [];
const single = [];
let count = 0;
for (const [n, slug] of [...slugByN].sort((a, b) => b[0] - a[0])) {
  const folder = folders.get(n);
  if (!folder) {
    missing.push({ n, slug });
    continue;
  }
  if (folder.files.length < 2) single.push({ n, slug, files: folder.files.length });
  images[slug] = [];
  for (let i = 0; i < folder.files.length; i++) {
    const name = `${slug}-${i + 1}.webp`;
    const out = path.join(OUT, name);
    const info = await sharp(folder.files[i])
      .resize({ width: MAX_WIDTH, withoutEnlargement: true })
      .webp({ quality: QUALITY })
      .toFile(out);
    images[slug].push({ src: `/blog/${name}`, width: info.width, height: info.height });
    count++;
  }
}

fs.writeFileSync(
  path.join(ROOT, "data/blog-images.ts"),
  `// Generated by tools/images.mjs from the client's image export. Do not edit by hand.\n` +
    `import type { ImageSource } from "./types";\n\n` +
    `export const blogImages: Record<string, ImageSource[]> = ${JSON.stringify(images, null, 2)};\n`,
);
const bytes = fs.readdirSync(OUT).reduce((s, f) => s + fs.statSync(path.join(OUT, f)).size, 0);
console.log(`[images] wrote ${count} files, ${(bytes / 1e6).toFixed(1)} MB total, ${Object.keys(images).length} posts`);
if (single.length) console.log("[images] posts with a single image:", single.map((s) => `#${s.n} ${s.slug}`).join(", "));
if (missing.length) console.log("[images] posts with no folder:", missing.map((s) => `#${s.n} ${s.slug}`).join(", "));
const unused = [...folders.keys()].filter((n) => !slugByN.has(n));
if (unused.length) console.log("[images] folders with no post:", unused.join(", "));
