/*
 * Redirect map generator (SEO brief, Phase 6).
 *
 *   node --experimental-strip-types tools/redirects.mjs
 *
 * Writes data/redirects.json from the URL changes the data remembers: the prototype's
 * /services paths, case-study ids (prototypeId) and repaired blog slugs (legacySlug).
 * Every entry is one hop to a page that exists; next.config.ts maps over the file with
 * permanent: true. Rows from a Search Console export of the previously indexed site go
 * in the "manual" section of the same file and are kept across regenerations.
 */
import fs from "node:fs";
import path from "node:path";
import { ROUTES } from "./slugs.mjs";

const ROOT = path.resolve(import.meta.dirname, "..");
const OUT = path.join(ROOT, "data/redirects.json");
const { blogPosts } = await import("../data/blog-posts.ts");
const { caseStudies } = await import("../data/case-studies.ts");

const generated = [];
// the prototype's /services section is /engineering now
for (const [id, dest] of Object.entries(ROUTES)) {
  if (id.startsWith("svc-")) generated.push({ source: `/services/${dest.split("/")[2]}`, destination: dest });
}
for (const c of caseStudies) {
  if (c.prototypeId !== c.slug) generated.push({ source: `/case-studies/${c.prototypeId}`, destination: `/case-studies/${c.slug}/` });
}
for (const p of blogPosts) {
  if (p.legacySlug && p.legacySlug !== p.slug) generated.push({ source: `/blog/${p.legacySlug}`, destination: `/blog/${p.slug}/` });
}

const previous = fs.existsSync(OUT) ? JSON.parse(fs.readFileSync(OUT, "utf8")) : {};
const manual = previous.manual ?? [];

const all = [...generated, ...manual];
const sources = new Set(all.map((r) => r.source));
for (const r of all) {
  if (!r.source.startsWith("/") || r.source.endsWith("/")) throw new Error(`source must be a bare path without trailing slash: ${r.source}`);
  if (!r.destination.startsWith("/") || !r.destination.endsWith("/")) throw new Error(`destination must be the canonical /path/ form: ${r.destination}`);
  // one hop: a destination is never itself redirected
  if (sources.has(r.destination.replace(/\/$/, ""))) throw new Error(`redirect chain: ${r.source} -> ${r.destination} -> ...`);
}
const dup = all.map((r) => r.source).filter((v, i, a) => a.indexOf(v) !== i);
if (dup.length) throw new Error(`duplicate sources: ${dup.join(", ")}`);

fs.writeFileSync(
  OUT,
  JSON.stringify(
    {
      $comment:
        "Generated by tools/redirects.mjs. 'generated' is regenerated from the data each time; add rows from the Search Console export under 'manual' (source without trailing slash, destination in /path/ form). next.config.ts serves both with permanent: true.",
      generated,
      manual,
    },
    null,
    2,
  ) + "\n",
);
console.log(`[redirects] generated ${generated.length}, manual ${manual.length}`);
