// Phase 1 proposal generator: writes docs/seo-url-map.md. Proposal only; renames nothing.
//   node --experimental-strip-types tools/url-map.mjs
import fs from "node:fs";
import { CASE_STUDY_SLUGS, BLOG_SLUG_REPAIRS } from "./slugs.mjs";
const { blogPosts } = await import("../data/blog-posts.ts");
const { caseStudies } = await import("../data/case-studies.ts");

const titleOf = (file) => (fs.readFileSync(file, "utf8").match(/title: "([^"]+)"/) || [])[1] || "";
const staticRows = [
  ["/", "/", "home", "app/page.tsx"],
  ["/pyzo", "/pyzo/", "pyzo landing", "app/pyzo/page.tsx"],
  ...["atlas", "compass", "evio", "forge", "loupe", "prism"].map((p) => [`/pyzo/${p}`, `/pyzo/${p}/`, "pyzo capability", `app/pyzo/${p}/page.tsx`]),
  ...["agentic-ai", "ai-governance", "enterprise-ai"].map((s) => [`/services/${s}`, `/engineering/${s}/`, "engineering", `app/services/${s}/page.tsx`]),
  ...["bfsi", "healthcare", "public-sector", "retail"].map((s) => [`/industries/${s}`, `/industries/${s}/`, "industry", `app/industries/${s}/page.tsx`]),
  ["/case-studies", "/case-studies/", "listing", "app/case-studies/page.tsx"],
  ["/blog", "/blog/", "listing", "app/blog/page.tsx"],
  ["/reports", "/reports/", "listing", "app/reports/page.tsx"],
  ["/about", "/about/", "company", "app/about/page.tsx"],
  ["/careers", "/careers/", "company", "app/careers/page.tsx"],
  ["/careers/apply", "/careers/apply/", "utility (noindex)", "app/careers/apply/page.tsx"],
  ["/contact", "/contact/", "company", "app/contact/page.tsx"],
  ["/technology", "/technology/", "company", "app/technology/page.tsx"],
  ["/privacy", "/privacy/", "legal", "app/privacy/page.tsx"],
  ["/terms", "/terms/", "legal", "app/terms/page.tsx"],
].map(([cur, prop, type, file]) => ({ cur, prop, type, title: titleOf(file) }));

// once the map is applied, the data carries the new slug and remembers the prototype one
const csRows = caseStudies.map((c) => ({
  cur: `/case-studies/${c.prototypeId ?? c.slug}`,
  prop: `/case-studies/${CASE_STUDY_SLUGS[c.prototypeId ?? c.slug]}/`,
  type: "case study",
  title: c.metaTitle,
}));
const blogRows = blogPosts.map((p) => {
  const cur = p.legacySlug ?? p.slug;
  const fix = BLOG_SLUG_REPAIRS[cur];
  return {
    cur: `/blog/${cur}`,
    prop: `/blog/${fix || cur}/`,
    type: fix ? (cur.length >= 58 ? "blog (repaired: truncated)" : "blog (repaired: apostrophe)") : "blog",
    title: p.metaTitle,
  };
});

const all = [...staticRows, ...csRows, ...blogRows];
const dup = all.map((r) => r.prop).filter((v, i, a) => a.indexOf(v) !== i);
if (dup.length) throw new Error("duplicate proposed URLs: " + dup);
const esc = (s) => s.replace(/\|/g, "\\|");
const table = (rows) =>
  ["| Current route | Proposed URL | Page type | Current title |", "|---|---|---|---|", ...rows.map((r) => `| \`${r.cur}\` | \`${r.prop}\` | ${r.type} | ${esc(r.title)} |`)].join("\n");
const changed = all.filter((r) => r.prop !== r.cur + "/" && r.cur !== "/");
const repaired = blogRows.filter((r) => r.type !== "blog");
const out = `# SEO Phase 1: URL map (proposal)

Status: **proposal, awaiting sign-off. Nothing has been renamed.**
Generated by \`tools/url-map.mjs\` from the content in \`data/\` and the route files in \`app/\`.

Totals: ${all.length} routes (${staticRows.length} static pages, ${csRows.length} case studies, ${blogRows.length} blog articles). ${all.length} unique proposed URLs. ${changed.length} routes change beyond the trailing slash.

## Decisions embedded in this map

1. **Trailing slash: on.** \`trailingSlash: true\` in \`next.config.ts\`; every canonical, sitemap entry and internal link uses the slash form. Next.js 308-redirects the bare form.
2. \`/services/*\` becomes \`/engineering/*\` to match the navigation label and the brief's shape.
3. Case-study slugs become the client name rather than the prototype id.
4. Blog slugs are kept as they are except where the prototype damaged them: 27 truncated at 58 characters, 4 with apostrophe fragments (\`-s-\`, \`-t\`). No category segment, no dates.
5. \`/people/\` is not proposed: there is no people page in the prototype (its \`people\` id aliased to About, and the leadership cards live on \`/about/\`).
6. \`/reports/\` is not in the brief's shape but exists as a page; kept.

## Static pages and case studies

${table([...staticRows, ...csRows])}

## Blog articles with a repaired slug (${repaired.length})

${table(repaired)}

## Blog articles, unchanged slug (${blogRows.length - repaired.length})

${table(blogRows.filter((r) => r.type === "blog"))}
`;
fs.mkdirSync("docs", { recursive: true });
fs.writeFileSync("docs/seo-url-map.md", out);
console.log({ total: all.length, changed: changed.length, repaired: repaired.length });
